// CV Oluşturucu arayüz metinleri — TR (varsayılan) ve EN.
// Site genelindeki dil anahtarı (lib/i18n) ile birlikte döner.
// Not: ATS ailesinin belgeye bastığı metinler (başlıklar, ay adları) burada değil,
// belge diline (settings.docLang) bağlı olarak lib/cv/doc-text.ts'te durur.
// Design ailesi `sections`, `f.*` ve `present` anahtarlarını belge diliyle (cvText(docLang)) basar.
import type { Lang } from '@/lib/i18n/config'
import type { BulletStyle, FontKey, HeadingStyle, SectionKey } from './types'
import type { TplCategory, TplFamily, TplRegion } from './templates'

const TR = {
  appTitle: 'CV Stüdyosu',
  appSub: 'ATS uyumlu ya da görsel bir şablon seç, bilgilerini gir, ince ayar yap; seçtiğin şablona göre ATS skorunu gör ve PDF/DOCX olarak indir.',
  freeBadge: 'Ücretsiz · ATS skoru · Kayıt yok · Veriler cihazında kalır',

  loader: {
    brand: 'CV Stüdyosu',
    lines: [
      'Şablon kütüphanesi hazırlanıyor',
      'ATS uyumlu ve görsel şablonlar yükleniyor',
      'Sayfa yerleşimi ölçekleniyor',
      'Çalışma alanı açılıyor',
    ],
    ready: 'Hazır',
  },

  steps: [
    { title: 'Şablon', sub: '' },
    { title: 'Bilgiler', sub: 'Alanları doldur' },
    { title: 'Düzenle', sub: 'İnce ayar' },
    { title: 'ATS & İndir', sub: 'Skor · PDF · DOCX' },
  ],
  stepOf: (i: number, n: number) => `Adım ${i} / ${n}`,
  cancel: 'Vazgeç',
  next: 'Devam',
  back: 'Geri',
  finish: 'ATS Skoruna Geç',

  /** Şablon aileleri — galeri filtresi ve rozetler. */
  families: {
    ats: 'ATS uyumlu',
    design: 'Görsel tasarım',
  } as Record<TplFamily, string>,

  gallery: {
    title: 'Bir şablonla başla',
    desc: (n: number, ats = 25) =>
      `${n} şablon: Ankara ilçelerinden ${ats} ATS uyumlu şablon (tek kolon, standart font ve başlıklar — en yüksek ATS skoru) ve Elazığ, Malatya, Kastamonu, Bayburt, Erzurum ve Artvin ilçelerinden ${n - ats} görsel şablon. Son adımdaki ATS skoru seçtiğin şablonun gerçek yerleşimine göre hesaplanır; şablonu istediğin an değiştirebilirsin.`,
    search: 'Şablon, il, stil ya da tür ara…',
    all: 'Tümü',
    allFamilies: 'Tüm şablonlar',
    allRegions: 'Tüm iller',
    familyFilter: 'Şablon türü',
    regionFilter: 'İl',
    categoryFilter: 'Stil',
    empty: 'Bu filtreye uyan şablon yok.',
    use: 'Bu şablonu kullan',
    continue: 'Devam et',
    selected: 'Seçili',
    select: 'Seç',
    preview: 'Büyüt',
    previewTitle: 'Şablon önizleme',
    count: (n: number) => `${n} şablon`,
    liveNote: 'Kartlardaki önizlemeler gerçek şablonun küçültülmüş halidir.',
    atsBadge: 'ATS uyumlu',
    atsBadgeTitle: 'ATS uyumlu: tek kolon, tablo/ikon/görsel yok, standart font ve başlıklar',
    designBadge: 'Görsel',
    designBadgeTitle: 'Görsel şablon — ATS skoru düşük olabilir',
    designNote:
      'Görsel şablonlar göz alıcıdır ama sütunlar, fotoğraf, seviye göstergeleri ve ikonlar ATS skorunu düşürebilir. Otomatik elemeden geçmesi gereken başvurularda ATS uyumlu bir şablon seç.',
  },

  form: {
    title: 'Bilgilerini gir',
    desc: 'Boş bıraktığın bölümler CV’de görünmez. Her şey anlık olarak önizlemeye yansır. Gerçek olmayan teknoloji, şirket ya da metrik yazma.',
    previewTab: 'Önizleme',
    formTab: 'Form',
    fillSample: 'Örnek veriyle doldur',
    clearAll: 'Tümünü temizle',
    clearConfirm: 'Girdiğin tüm bilgiler silinecek. Devam edilsin mi?',
    exportJson: 'Yedek al (JSON)',
    importJson: 'Yedeği yükle',
    importError: 'Dosya okunamadı — geçerli bir CV yedeği değil.',
    add: 'Ekle',
    remove: 'Sil',
    moveUp: 'Yukarı taşı',
    moveDown: 'Aşağı taşı',
    empty: 'Henüz kayıt yok.',

    photoAdd: 'Fotoğraf yükle',
    photoChange: 'Değiştir',
    photoRemove: 'Kaldır',
    photoHint: 'JPG/PNG · tarayıcıda 480px’e küçültülür, sunucuya gönderilmez.',
    photoError: 'Görsel okunamadı.',
    photoDesignOnly: 'Yalnızca görsel şablonlarda basılır; ATS için fotoğraf önerilmez.',

    titleHint: 'Başvurduğun ilandaki pozisyon adını birebir yaz (ör. “Senior Backend Developer”).',
    summaryHint:
      '2–4 cümle. “Ben/benim” gibi birinci tekil kullanma. Deneyim yılını, uzmanlık alanını, temel teknolojileri ve somut bir etkiyi yaz.',
    summaryStats: (sentences: number, words: number) => `${sentences} cümle · ${words} kelime`,
    summaryLength: 'Profesyonel özet için 2–4 cümle önerilir.',
    firstPerson: (words: string) => `Birinci tekil ifade bulundu (${words}). Özeti öznesiz yaz: “8 yıllık deneyime sahip Backend Developer…”`,

    bulletsHint: 'Her satır bir madde: Eylem + Teknoloji + Ne geliştirildi + Sonuç. Gerçek olmayan metrik yazma.',
    bulletsCount: (n: number) => `${n} madde`,
    bulletsRange: 'Her deneyim için 3–6 madde önerilir.',

    dateInvalid: 'Tarih tanınmadı — AA/YYYY biçiminde yaz (ör. 01/2024).',
    langLevelHint: 'CEFR seviyesi + açıklama önerilir.',
    skillGroupHint: 'Aynı gruptaki yetkinlikler CV’de tek satırda listelenir.',
    skillsHint: 'Yetkinlikleri kategoriye göre grupla (Programlama Dilleri, Backend, Veritabanları…). ATS şablonlarında seviye çubuğu ya da puan basılmaz.',
    skillsHintDesign:
      'Yetkinlikleri kategoriye göre grupla (Programlama Dilleri, Backend, Veritabanları…). Seviye kaydırıcıları yalnızca görsel şablonun göstergelerini çizer.',
    levelAtsNote: 'Seviye göstergeleri ATS’de okunmaz; skor için metin (ör. “C1 (İleri)”) önemlidir.',
    levelLabel: (n: number) => ['—', 'Başlangıç', 'Temel', 'İyi', 'İleri', 'Uzman'][n] ?? '—',
    bulkTitle: 'Toplu ekle',
    bulkGroup: 'Grup',
    bulkPlaceholder: 'Java, Spring Boot, Hibernate',
    bulkHint: 'Virgülle ya da satır satır ayır; seçtiğin gruba eklenir, tekrar edenler atlanır.',
    bulkAdd: 'Gruba ekle',
    bulkAdded: (n: number) => (n > 0 ? `${n} yetkinlik eklendi` : 'Eklenecek yeni yetkinlik yok'),
    techHint: 'Virgülle ayır: React, Spring Boot, PostgreSQL',
    projectSummaryHint: 'Projenin ne olduğunu tek cümleyle anlat.',
    highlightsHint: 'Her satır bir madde: senin katkın ve somut sonuç.',
    extraTitle: 'Ek bilgiler (opsiyonel)',
    extraHint:
      'ATS ve uluslararası başvurularda doğum tarihi, uyruk, ehliyet ve askerlik bilgisi genellikle gerekmez. Yalnızca ilan açıkça istiyorsa doldur.',

    interestsHint: 'Virgülle ayır: Satranç, Koşu, Fotoğrafçılık',
    current: 'Devam ediyor',
    required: 'Zorunlu değil ama CV’yi güçlendirir.',
    savedAt: (t: string) => `Otomatik kaydedildi · ${t}`,
  },

  editor: {
    title: 'İnce ayar yap',
    desc: 'Dil, renk, tipografi, yerleşim ve bölüm sırasını değiştir. Değişiklikler anında önizlemeye işler; ATS skoru son adımda seçili şablona göre hesaplanır.',
    tabDesign: 'Tasarım',
    tabSections: 'Bölümler',
    tabTemplate: 'Şablon',

    atsSafeTitle: 'ATS uyumlu şablon',
    atsSafeDesc:
      'Bu ayarlar CV’nin ATS uyumunu bozamaz: kolon, tablo, fotoğraf, ikon ya da grafik seçeneği yoktur; boyutlar ve boşluklar standart aralıklarla sınırlıdır.',

    /** Görsel şablon seçiliyken gösterilen ATS etkisi kartı ve riskli kontrol uyarıları. */
    atsImpact: {
      title: 'ATS etkisi',
      desc: 'Bu görsel bir şablon. ATS sistemleri sütunları, fotoğrafı, seviye göstergelerini, ikonları ve standart dışı fontları yanlış okuyabilir. Son adımdaki ATS skoru bu şablonun gerçek yerleşimini yansıtır.',
      action: 'ATS uyumlu şablona geç',
      columns: 'Yan sütunlu ya da iki sütunlu yerleşim ATS’de okuma sırasını bozabilir.',
      photo: 'Fotoğraf ATS skorunu düşürür.',
      meters: 'Çubuk, nokta ve halka göstergeleri ATS’de okunmaz ve skoru düşürür; “Metin” ya da “Rozet” daha güvenli.',
      icons: 'İletişim ikonları ATS skorunu düşürür.',
      font: 'Standart dışı font ATS skorunu düşürür; ATS standart fontlarından birini seç.',
    },

    groupLang: 'CV dili',
    docLang: 'Belge dili',
    docLangs: { tr: 'Türkçe', en: 'English' },
    docLangHint: 'Bölüm başlıkları, ay adları ve “Günümüz / Present” bu dile göre basılır.',

    groupColor: 'Renk ve ton',
    accent: 'Vurgu rengi',
    accentReset: 'Şablon rengine dön',
    accentHint: 'Renk yalnızca ad ve başlıklarda sınırlı bir vurgudur; hiçbir bilgi renge bağlı değildir.',
    accentLowContrast: (ratio: string) =>
      `Bu renk beyaz zeminde yeterince koyu değil (kontrast ${ratio}:1, en az 4.5:1 olmalı). Daha koyu bir ton seç.`,
    rail: 'Yan sütun rengi',
    railReset: 'Şablon tonu',
    paperTint: 'Kâğıt tonu',
    paperTints: { template: 'Şablon', white: 'Beyaz', cream: 'Krem', gray: 'Gri' },
    inkTone: 'Metin tonu',
    inkTones: { template: 'Şablon', slate: 'Füme', black: 'Siyah', navy: 'Lacivert', warm: 'Sıcak' },

    groupType: 'Tipografi',
    font: 'Gövde yazı tipi',
    headingFont: 'Başlık yazı tipi',
    fontRowDesign: 'Tasarım fontları',
    fontRowAts: 'ATS standart fontları',
    fonts: {
      sans: 'Modern (Inter)',
      serif: 'Klasik (Source Serif 4)',
      mono: 'Teknik (JetBrains Mono)',
      display: 'İddialı (Space Grotesk)',
      arial: 'Arial — ATS standart',
      calibri: 'Calibri — ATS standart',
      helvetica: 'Helvetica — ATS standart',
      georgia: 'Georgia — ATS standart',
      cambria: 'Cambria — ATS standart',
      times: 'Times New Roman — ATS standart',
    } as Record<FontKey, string>,
    fontHint:
      'Yalnızca ATS’lerin sorunsuz okuduğu standart fontlar. Calibri ya da Cambria cihazında yüklü değilse tarayıcı metrik uyumlu (Carlito/Caladea) ya da ATS güvenli bir yedek fonta geçer.',
    fontScale: 'Yazı boyutu',
    headingScale: 'Başlık boyutu',
    letterSpacing: 'Harf aralığı',
    bodySize: 'Gövde metni',
    headingSize: 'Bölüm başlıkları',
    nameSize: 'Ad Soyad',
    lineHeight: 'Satır aralığı',

    groupLayout: 'Yerleşim',
    margin: 'Kenar boşluğu',
    sectionGap: 'Bölüm aralığı',
    paper: 'Kâğıt',
    justify: 'Özeti iki yana yasla',
    headingStyle: 'Başlık biçimi',
    headingStyles: {
      rule: 'Alt çizgi',
      'caps-rule': 'BÜYÜK + çizgi',
      caps: 'BÜYÜK HARF',
      overline: 'Üst çizgi',
      underline: 'Altı çizili',
      smallcaps: 'Küçük büyük harf',
      plain: 'Sade kalın',
    } as Record<HeadingStyle, string>,
    headerAlign: 'Başlık hizası',
    headerAligns: { left: 'Sola', center: 'Ortaya' },
    contactSeparator: 'İletişim ayracı',
    dateFormat: 'Tarih biçimi',
    datePosition: 'Tarih konumu',
    datePositions: { right: 'Sağa yaslı', inline: 'Satır içinde' },
    entryOrder: 'Deneyim sırası',
    entryOrders: { 'title-first': 'Önce pozisyon', 'company-first': 'Önce şirket' },

    groupPhoto: 'Fotoğraf',
    photoToggle: 'Fotoğrafı göster',
    photoShape: 'Fotoğraf çerçevesi',
    photoShapes: { '': 'Şablon', circle: 'Yuvarlak', square: 'Kare', rounded: 'Yumuşak köşe' },
    photoSize: 'Fotoğraf boyutu',
    photoNone: 'Bu şablon fotoğrafsız tasarlandı; çerçeve seçersen yine de eklenir.',

    groupDetails: 'Ayrıntılar',
    skillStyle: 'Yetenek göstergesi',
    skillStyles: { '': 'Şablon', bar: 'Çubuk', dots: 'Nokta', chips: 'Rozet', text: 'Metin', ring: 'Halka' },
    bulletStyle: 'Madde işareti',
    bulletStyles: { dot: '• Nokta', square: '▪ Kare', dash: '– Tire', arrow: '→ Ok', check: '✓ Onay' } as Record<BulletStyle, string>,
    iconsToggle: 'İletişim ikonlarını göster',

    reset: 'Şablon varsayılanlarına dön',
    orderTitle: 'Bölüm sırası ve görünürlük',
    orderHint: 'Sürükleyerek ya da okları kullanarak sırala. Göz simgesi bölümü gizler, sayfa simgesi bölümü yeni sayfada başlatır.',
    pageBreakOn: 'Yeni sayfada başlat',
    pageBreakOff: 'Sayfa başını kaldır',
    rename: 'Bölüm başlıkları',
    renameHint: 'ATS’ler standart başlıkları tanır. Boş bıraktığında CV dilindeki standart başlık kullanılır.',
    nonStandard: 'Standart dışı başlık — ATS tanımayabilir',
    backToStandard: 'Standarda dön',
    show: 'Göster',
    hide: 'Gizle',
    emptyBadge: 'boş',
    changeTemplate: 'Şablonu değiştir',
    zoom: 'Yakınlaştırma',
    fit: 'Sığdır',
  },

  exportStep: {
    title: 'CV’n hazır',
    desc: 'PDF çıktısı tarayıcının kendi yazdırma motoruyla alınır: metin seçilebilir ve ATS’ler tarafından okunabilir. Word (DOCX) ve düz metin çıktıları da aynı içeriği taşır.',
    download: 'PDF olarak indir',
    downloadDocx: 'Word (DOCX) olarak indir',
    downloadTxt: 'Düz metin (TXT)',
    preparing: 'Çıktı hazırlanıyor…',
    fileName: 'Dosya adı',
    formatsTitle: 'Biçimler',
    tipsTitle: 'Kusursuz PDF için',
    tips: [
      'Açılan pencerede hedef olarak “PDF olarak kaydet” seçili olmalı.',
      'Kenar boşluğu “Yok” ya da “Varsayılan”, ölçek %100 olarak bırakılmalı — sayfa boşlukları CV’nin içinde zaten ayarlı.',
      '“Üst bilgi ve alt bilgi” seçeneğini KAPAT; aksi halde tarayıcı sayfaya adres ve tarih ekler.',
      '“Arka plan grafikleri” gerekmez — CV beyaz zeminli ve tamamen metin tabanlıdır.',
      'Telefonda: Paylaş → Yazdır → PDF olarak kaydet.',
    ],
    /** Görsel şablonlar için yazdırma ipuçları — renkli zeminler "Arka plan grafikleri" ister. */
    tipsDesign: [
      'Açılan pencerede hedef olarak “PDF olarak kaydet” seçili olmalı.',
      'Kenar boşluğu “Yok”, ölçek %100 olarak bırakılmalı.',
      '“Arka plan grafikleri” seçeneğini İŞARETLE — renkli bantlar, yan sütunlar ve göstergeler ancak bu sayede basılır.',
      '“Üst bilgi ve alt bilgi” seçeneğini KAPAT; aksi halde tarayıcı sayfaya adres ve tarih ekler.',
      'Telefonda: Paylaş → Yazdır → parmakla büyüt → PDF olarak kaydet.',
    ],
    pages: (n: number) => `${n} sayfa`,
    backupTitle: 'Yedek',
    backupDesc: 'Bilgilerini JSON olarak indir; sonra istediğin an geri yükleyip farklı bir şablonla yeniden üret.',
    startOver: 'Yeni CV oluştur',
    startOverConfirm: 'Mevcut CV silinip sıfırdan başlanacak. Devam edilsin mi?',
    templateLabel: 'Şablon',
  },

  sections: {
    summary: 'Profesyonel Özet',
    experience: 'İş Deneyimi',
    education: 'Eğitim',
    skills: 'Teknik Yetkinlikler',
    languages: 'Yabancı Dil',
    projects: 'Projeler',
    certificates: 'Sertifikalar',
    awards: 'Ödüller',
    interests: 'İlgi Alanları',
    references: 'Referanslar',
  } as Record<SectionKey, string>,

  categories: {
    corporate: 'Kurumsal',
    modern: 'Modern',
    minimal: 'Minimal',
    executive: 'Yönetici',
    creative: 'Yaratıcı',
    technical: 'Teknik',
    academic: 'Akademik',
  } as Record<TplCategory, string>,

  regions: {
    ankara: 'Ankara',
    elazig: 'Elazığ',
    malatya: 'Malatya',
    kastamonu: 'Kastamonu',
    bayburt: 'Bayburt',
    erzurum: 'Erzurum',
    artvin: 'Artvin',
  } as Record<TplRegion, string>,

  f: {
    identity: 'Kimlik',
    contact: 'İletişim',
    fullName: 'Ad Soyad',
    jobTitle: 'Profesyonel unvan',
    photo: 'Fotoğraf',
    summary: 'Profesyonel özet',
    email: 'E-posta',
    phone: 'Telefon',
    location: 'Şehir',
    website: 'Portföy / Web sitesi',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    birthDate: 'Doğum tarihi',
    nationality: 'Uyruk',
    drivingLicense: 'Ehliyet',
    military: 'Askerlik',
    role: 'Pozisyon',
    company: 'Şirket',
    start: 'Başlangıç',
    end: 'Bitiş',
    achievements: 'Başarılar ve sorumluluklar',
    degree: 'Bölüm / Derece',
    school: 'Okul',
    grade: 'Not ortalaması',
    skillName: 'Yetkinlik',
    group: 'Kategori',
    level: 'Seviye',
    langName: 'Dil',
    langLevel: 'Seviye',
    projectName: 'Proje adı',
    link: 'Bağlantı',
    tech: 'Teknolojiler',
    highlights: 'Temel katkı / sonuç',
    certName: 'Sertifika',
    issuer: 'Kurum',
    date: 'Tarih',
    awardName: 'Ödül',
    refName: 'Ad Soyad',
    refContact: 'İletişim',
    description: 'Kısa açıklama',
  },

  present: 'Devam ediyor',
  a11yPreview: 'CV önizlemesi',
}

const EN: typeof TR = {
  appTitle: 'CV Studio',
  appSub: 'Pick an ATS-friendly or a visual template, fill in your details, fine-tune it, see the ATS score for the template you chose and download PDF/DOCX.',
  freeBadge: 'Free · ATS score · No sign-up · Your data stays on your device',

  loader: {
    brand: 'CV Studio',
    lines: [
      'Preparing the template library',
      'Loading ATS-compliant and visual templates',
      'Scaling the page layout',
      'Opening your workspace',
    ],
    ready: 'Ready',
  },

  steps: [
    { title: 'Template', sub: '' },
    { title: 'Details', sub: 'Fill the fields' },
    { title: 'Refine', sub: 'Fine-tune' },
    { title: 'ATS & Download', sub: 'Score · PDF · DOCX' },
  ],
  stepOf: (i: number, n: number) => `Step ${i} of ${n}`,
  cancel: 'Cancel',
  next: 'Continue',
  back: 'Back',
  finish: 'See ATS score',

  families: {
    ats: 'ATS compliant',
    design: 'Visual design',
  },

  gallery: {
    title: 'Start with a template',
    desc: (n: number, ats = 25) =>
      `${n} templates: ${ats} ATS-compliant templates named after districts of Ankara (single column, standard fonts and headings — the highest ATS score) and ${n - ats} visual templates named after districts of Elazığ, Malatya, Kastamonu, Bayburt, Erzurum and Artvin. The ATS score in the last step is calculated for the real layout of the template you choose, and you can switch templates at any time.`,
    search: 'Search by template, province, style or type…',
    all: 'All',
    allFamilies: 'All templates',
    allRegions: 'All provinces',
    familyFilter: 'Template type',
    regionFilter: 'Province',
    categoryFilter: 'Style',
    empty: 'No template matches this filter.',
    use: 'Use this template',
    continue: 'Continue',
    selected: 'Selected',
    select: 'Select',
    preview: 'Enlarge',
    previewTitle: 'Template preview',
    count: (n: number) => `${n} templates`,
    liveNote: 'Card previews are the real template, scaled down.',
    atsBadge: 'ATS compliant',
    atsBadgeTitle: 'ATS compliant: single column, no tables/icons/images, standard fonts and headings',
    designBadge: 'Visual',
    designBadgeTitle: 'Visual template — the ATS score may be lower',
    designNote:
      'Visual templates stand out, but columns, photos, skill meters and icons can lower the ATS score. For applications that must pass automated screening, pick an ATS-compliant template.',
  },

  form: {
    title: 'Fill in your details',
    desc: 'Sections you leave empty stay off the CV. Everything updates in the preview as you type. Never add technologies, companies or metrics that are not real.',
    previewTab: 'Preview',
    formTab: 'Form',
    fillSample: 'Fill with sample data',
    clearAll: 'Clear everything',
    clearConfirm: 'Every detail you entered will be deleted. Continue?',
    exportJson: 'Back up (JSON)',
    importJson: 'Load a backup',
    importError: 'Could not read the file — it is not a valid CV backup.',
    add: 'Add',
    remove: 'Delete',
    moveUp: 'Move up',
    moveDown: 'Move down',
    empty: 'Nothing here yet.',

    photoAdd: 'Upload a photo',
    photoChange: 'Change',
    photoRemove: 'Remove',
    photoHint: 'JPG/PNG · resized to 480px in the browser, never uploaded.',
    photoError: 'Could not read the image.',
    photoDesignOnly: 'Printed only by visual templates; photos are not recommended for ATS.',

    titleHint: 'Use the exact job title from the posting (e.g. “Senior Backend Developer”).',
    summaryHint:
      '2–4 sentences, no first person (“I”, “my”). Mention years of experience, area of expertise, key technologies and a concrete impact.',
    summaryStats: (sentences: number, words: number) =>
      `${sentences} sentence${sentences === 1 ? '' : 's'} · ${words} word${words === 1 ? '' : 's'}`,
    summaryLength: 'A professional summary works best at 2–4 sentences.',
    firstPerson: (words: string) => `First-person wording found (${words}). Write without a subject: “Backend Developer with 8 years of experience…”`,

    bulletsHint: 'One bullet per line: Action + Technology + What was built/improved + Result. Never invent metrics.',
    bulletsCount: (n: number) => `${n} bullet${n === 1 ? '' : 's'}`,
    bulletsRange: '3–6 bullets per role are recommended.',

    dateInvalid: 'Date not recognised — use MM/YYYY (e.g. 01/2024).',
    langLevelHint: 'A CEFR level plus a description is recommended.',
    skillGroupHint: 'Skills in the same category are listed on one line in the CV.',
    skillsHint: 'Group skills by category (Languages, Backend, Databases…). ATS templates never print skill bars or ratings.',
    skillsHintDesign:
      'Group skills by category (Languages, Backend, Databases…). The level sliders only drive the meters of the visual template.',
    levelAtsNote: 'ATS software cannot read level meters; for the score, the text (e.g. “C1 (Advanced)”) is what counts.',
    levelLabel: (n: number) => ['—', 'Beginner', 'Basic', 'Good', 'Advanced', 'Expert'][n] ?? '—',
    bulkTitle: 'Add several',
    bulkGroup: 'Category',
    bulkPlaceholder: 'Java, Spring Boot, Hibernate',
    bulkHint: 'Separate with commas or new lines; they are added to the chosen category and duplicates are skipped.',
    bulkAdd: 'Add to category',
    bulkAdded: (n: number) => (n > 0 ? `${n} skill${n === 1 ? '' : 's'} added` : 'No new skills to add'),
    techHint: 'Comma separated: React, Spring Boot, PostgreSQL',
    projectSummaryHint: 'Describe the project in one sentence.',
    highlightsHint: 'One bullet per line: your contribution and the concrete result.',
    extraTitle: 'Additional details (optional)',
    extraHint:
      'Date of birth, nationality, driving licence and military service are usually not needed for ATS or international applications. Fill them in only if the posting asks.',

    interestsHint: 'Comma separated: Chess, Running, Photography',
    current: 'Ongoing',
    required: 'Optional, but it makes the CV stronger.',
    savedAt: (t: string) => `Saved automatically · ${t}`,
  },

  editor: {
    title: 'Fine-tune it',
    desc: 'Change language, colour, typography, layout and section order. Every change lands in the preview instantly; the ATS score in the last step is calculated for the selected template.',
    tabDesign: 'Design',
    tabSections: 'Sections',
    tabTemplate: 'Template',

    atsSafeTitle: 'ATS-compliant template',
    atsSafeDesc:
      'These settings cannot break ATS compliance: there are no columns, tables, photos, icons or graphics to add, and sizes and spacing are limited to standard ranges.',

    atsImpact: {
      title: 'ATS impact',
      desc: 'This is a visual template. ATS software may misread columns, photos, skill meters, icons and non-standard fonts. The ATS score in the last step reflects this template’s real layout.',
      action: 'Switch to an ATS-compliant template',
      columns: 'Sidebar or two-column layouts can scramble the reading order in ATS software.',
      photo: 'A photo lowers the ATS score.',
      meters: 'Bar, dot and ring meters cannot be read by ATS software and lower the score; “Text” or “Chips” are safer.',
      icons: 'Contact icons lower the ATS score.',
      font: 'A non-standard font lowers the ATS score; pick one of the ATS standard fonts.',
    },

    groupLang: 'CV language',
    docLang: 'Document language',
    docLangs: { tr: 'Türkçe', en: 'English' },
    docLangHint: 'Section headings, month names and “Present / Günümüz” follow this language.',

    groupColor: 'Colour and tone',
    accent: 'Accent colour',
    accentReset: 'Back to template colour',
    accentHint: 'Colour is only a limited accent on the name and headings; no information depends on it.',
    accentLowContrast: (ratio: string) =>
      `This colour is not dark enough on white (contrast ${ratio}:1, needs at least 4.5:1). Pick a darker shade.`,
    rail: 'Sidebar colour',
    railReset: 'Template tone',
    paperTint: 'Paper tone',
    paperTints: { template: 'Template', white: 'White', cream: 'Cream', gray: 'Grey' },
    inkTone: 'Text tone',
    inkTones: { template: 'Template', slate: 'Slate', black: 'Black', navy: 'Navy', warm: 'Warm' },

    groupType: 'Typography',
    font: 'Body typeface',
    headingFont: 'Heading typeface',
    fontRowDesign: 'Design fonts',
    fontRowAts: 'ATS standard fonts',
    fonts: {
      sans: 'Modern (Inter)',
      serif: 'Classic (Source Serif 4)',
      mono: 'Technical (JetBrains Mono)',
      display: 'Bold (Space Grotesk)',
      arial: 'Arial — ATS standard',
      calibri: 'Calibri — ATS standard',
      helvetica: 'Helvetica — ATS standard',
      georgia: 'Georgia — ATS standard',
      cambria: 'Cambria — ATS standard',
      times: 'Times New Roman — ATS standard',
    },
    fontHint:
      'Only standard fonts that ATS software reads reliably. If Calibri or Cambria is not installed, the browser falls back to a metric-compatible (Carlito/Caladea) or another ATS-safe font.',
    fontScale: 'Font size',
    headingScale: 'Heading size',
    letterSpacing: 'Letter spacing',
    bodySize: 'Body text',
    headingSize: 'Section headings',
    nameSize: 'Full name',
    lineHeight: 'Line height',

    groupLayout: 'Layout',
    margin: 'Page margin',
    sectionGap: 'Section spacing',
    paper: 'Paper',
    justify: 'Justify the summary',
    headingStyle: 'Heading style',
    headingStyles: {
      rule: 'Rule below',
      'caps-rule': 'CAPS + rule',
      caps: 'UPPERCASE',
      overline: 'Rule above',
      underline: 'Underlined',
      smallcaps: 'Small caps',
      plain: 'Plain bold',
    },
    headerAlign: 'Header alignment',
    headerAligns: { left: 'Left', center: 'Centre' },
    contactSeparator: 'Contact separator',
    dateFormat: 'Date format',
    datePosition: 'Date position',
    datePositions: { right: 'Right-aligned', inline: 'Inline' },
    entryOrder: 'Experience order',
    entryOrders: { 'title-first': 'Title first', 'company-first': 'Company first' },

    groupPhoto: 'Photo',
    photoToggle: 'Show the photo',
    photoShape: 'Photo frame',
    photoShapes: { '': 'Template', circle: 'Circle', square: 'Square', rounded: 'Rounded' },
    photoSize: 'Photo size',
    photoNone: 'This template was drawn without a photo; picking a frame adds one anyway.',

    groupDetails: 'Details',
    skillStyle: 'Skill meter',
    skillStyles: { '': 'Template', bar: 'Bar', dots: 'Dots', chips: 'Chips', text: 'Text', ring: 'Ring' },
    bulletStyle: 'Bullet mark',
    bulletStyles: { dot: '• Dot', square: '▪ Square', dash: '– Dash', arrow: '→ Arrow', check: '✓ Check' },
    iconsToggle: 'Show contact icons',

    reset: 'Reset to template defaults',
    orderTitle: 'Section order and visibility',
    orderHint: 'Drag, or use the arrows, to reorder. The eye icon hides a section; the page icon starts it on a new page.',
    pageBreakOn: 'Start on a new page',
    pageBreakOff: 'Remove the page break',
    rename: 'Section headings',
    renameHint: 'ATS software recognises standard headings. Leave a field empty to use the standard heading in the CV language.',
    nonStandard: 'Non-standard heading — ATS may not recognise it',
    backToStandard: 'Use standard',
    show: 'Show',
    hide: 'Hide',
    emptyBadge: 'empty',
    changeTemplate: 'Change template',
    zoom: 'Zoom',
    fit: 'Fit',
  },

  exportStep: {
    title: 'Your CV is ready',
    desc: 'The PDF comes from your browser’s own print engine: selectable text that ATS software can read. The Word (DOCX) and plain-text outputs carry exactly the same content.',
    download: 'Download as PDF',
    downloadDocx: 'Download as Word (DOCX)',
    downloadTxt: 'Plain text (TXT)',
    preparing: 'Preparing the output…',
    fileName: 'File name',
    formatsTitle: 'Formats',
    tipsTitle: 'For a flawless PDF',
    tips: [
      'In the dialog that opens, the destination must be “Save as PDF”.',
      'Leave margins on “None” or “Default” and the scale at 100% — page margins are already set inside the CV.',
      'Turn OFF “Headers and footers”, otherwise the browser adds the URL and date to the page.',
      '“Background graphics” is not required — the CV is white and entirely text-based.',
      'On a phone: Share → Print → Save as PDF.',
    ],
    tipsDesign: [
      'In the dialog that opens, the destination must be “Save as PDF”.',
      'Leave margins on “None” and the scale at 100%.',
      'TICK “Background graphics” — colour bands, sidebars and meters only print with it on.',
      'Turn OFF “Headers and footers”, otherwise the browser adds the URL and date to the page.',
      'On a phone: Share → Print → pinch to zoom → Save as PDF.',
    ],
    pages: (n: number) => `${n} page${n === 1 ? '' : 's'}`,
    backupTitle: 'Backup',
    backupDesc: 'Download your details as JSON, then load them back any time and rebuild with another template.',
    startOver: 'Create a new CV',
    startOverConfirm: 'The current CV will be deleted and you will start over. Continue?',
    templateLabel: 'Template',
  },

  sections: {
    summary: 'Professional Summary',
    experience: 'Work Experience',
    education: 'Education',
    skills: 'Technical Skills',
    languages: 'Languages',
    projects: 'Projects',
    certificates: 'Certifications',
    awards: 'Awards',
    interests: 'Interests',
    references: 'References',
  },

  categories: {
    corporate: 'Corporate',
    modern: 'Modern',
    minimal: 'Minimal',
    executive: 'Executive',
    creative: 'Creative',
    technical: 'Technical',
    academic: 'Academic',
  },

  regions: {
    ankara: 'Ankara',
    elazig: 'Elazığ',
    malatya: 'Malatya',
    kastamonu: 'Kastamonu',
    bayburt: 'Bayburt',
    erzurum: 'Erzurum',
    artvin: 'Artvin',
  },

  f: {
    identity: 'Identity',
    contact: 'Contact',
    fullName: 'Full name',
    jobTitle: 'Professional title',
    photo: 'Photo',
    summary: 'Professional summary',
    email: 'Email',
    phone: 'Phone',
    location: 'City',
    website: 'Portfolio / Website',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    birthDate: 'Date of birth',
    nationality: 'Nationality',
    drivingLicense: 'Driving licence',
    military: 'Military service',
    role: 'Job title',
    company: 'Company',
    start: 'Start',
    end: 'End',
    achievements: 'Achievements and responsibilities',
    degree: 'Programme / Degree',
    school: 'Institution',
    grade: 'GPA',
    skillName: 'Skill',
    group: 'Category',
    level: 'Level',
    langName: 'Language',
    langLevel: 'Level',
    projectName: 'Project name',
    link: 'Link',
    tech: 'Technologies',
    highlights: 'Key contribution / result',
    certName: 'Certification',
    issuer: 'Issuer',
    date: 'Date',
    awardName: 'Award',
    refName: 'Full name',
    refContact: 'Contact',
    description: 'Short description',
  },

  present: 'Ongoing',
  a11yPreview: 'CV preview',
}

export type CvText = typeof TR

export function cvText(lang: Lang): CvText {
  return lang === 'en' ? EN : TR
}
