// CV Oluşturucu arayüz metinleri — TR (varsayılan) ve EN.
// Site genelindeki dil anahtarı (lib/i18n) ile birlikte döner.
import type { Lang } from '@/lib/i18n/config'
import type { SectionKey } from './types'
import type { TplCategory } from './templates'

const TR = {
  appTitle: 'CV Stüdyosu',
  appSub: 'Şablon seç, bilgilerini gir, ince ayar yap, PDF olarak indir',
  freeBadge: 'Ücretsiz · Kayıt yok · Veriler cihazında kalır',

  loader: {
    brand: 'CV Stüdyosu',
    lines: [
      'Şablon kütüphanesi hazırlanıyor',
      'Tipografi ve renk paletleri yükleniyor',
      'Sayfa yerleşimi ölçekleniyor',
      'Çalışma alanı açılıyor',
    ],
    ready: 'Hazır',
  },

  steps: [
    { title: 'Şablon', sub: '' },
    { title: 'Bilgiler', sub: 'Alanları doldur' },
    { title: 'Düzenle', sub: 'İnce ayar' },
    { title: 'İndir', sub: 'PDF çıktısı' },
  ],
  stepOf: (i: number, n: number) => `Adım ${i} / ${n}`,
  cancel: 'Vazgeç',
  next: 'Devam',
  back: 'Geri',
  finish: 'PDF Adımına Geç',

  gallery: {
    title: 'Bir şablonla başla',
    desc: (n: number) =>
      `${n} profesyonel yerleşim — adları Elazığ, Malatya ve Kastamonu ilçelerinden geliyor. Seçtiğin şablonu sonraki adımlarda renk, tipografi ve bölüm sırasına kadar değiştirebilirsin.`,
    search: 'Şablon ara…',
    all: 'Tümü',
    empty: 'Bu filtreye uyan şablon yok.',
    use: 'Bu şablonu kullan',
    continue: 'Devam et',
    selected: 'Seçili',
    select: 'Seç',
    preview: 'Büyüt',
    previewTitle: 'Şablon önizleme',
    count: (n: number) => `${n} şablon`,
    liveNote: 'Kartlardaki önizlemeler gerçek şablonun küçültülmüş halidir.',
  },

  form: {
    title: 'Bilgilerini gir',
    desc: 'Boş bıraktığın bölümler CV’de görünmez. Her şey anlık olarak önizlemeye yansır.',
    previewTab: 'Önizleme',
    formTab: 'Form',
    fillSample: 'Örnek veriyle doldur',
    clearAll: 'Tümünü temizle',
    clearConfirm: 'Girdiğin tüm bilgiler silinecek. Devam edilsin mi?',
    exportJson: 'Yedek al (JSON)',
    importJson: 'Yedeği yükle',
    importError: 'Dosya okunamadı — geçerli bir CV yedeği değil.',
    add: 'Ekle',
    remove: 'Sil',
    moveUp: 'Yukarı taşı',
    moveDown: 'Aşağı taşı',
    empty: 'Henüz kayıt yok.',
    photoAdd: 'Fotoğraf yükle',
    photoChange: 'Değiştir',
    photoRemove: 'Kaldır',
    photoHint: 'JPG/PNG · tarayıcıda 480px’e küçültülür, sunucuya gönderilmez.',
    photoError: 'Görsel okunamadı.',
    bulletsHint: 'Her satır bir madde olur.',
    interestsHint: 'Virgülle ayır: Satranç, Koşu, Fotoğrafçılık',
    current: 'Devam ediyor',
    levelLabel: (n: number) => ['—', 'Başlangıç', 'Temel', 'İyi', 'İleri', 'Uzman'][n] ?? '—',
    required: 'Zorunlu değil ama CV’yi güçlendirir.',
    savedAt: (t: string) => `Otomatik kaydedildi · ${t}`,
  },

  editor: {
    title: 'İnce ayar yap',
    desc: 'Renk, tipografi, yoğunluk ve bölüm sırasını değiştir. Değişiklikler anında önizlemeye işler.',
    tabDesign: 'Tasarım',
    tabSections: 'Bölümler',
    tabTemplate: 'Şablon',
    accent: 'Vurgu rengi',
    accentReset: 'Şablon rengine dön',
    groupColor: 'Renk ve ton',
    groupType: 'Tipografi',
    groupLayout: 'Yerleşim',
    groupPhoto: 'Fotoğraf',
    groupDetails: 'Ayrıntılar',
    rail: 'Yan sütun rengi',
    railReset: 'Şablon tonu',
    paperTint: 'Kâğıt tonu',
    paperTints: { template: 'Şablon', white: 'Beyaz', cream: 'Krem', gray: 'Gri' },
    inkTone: 'Metin tonu',
    inkTones: { template: 'Şablon', slate: 'Füme', black: 'Siyah', navy: 'Lacivert', warm: 'Sıcak' },
    headingFont: 'Başlık yazı tipi',
    headingScale: 'Başlık boyutu',
    letterSpacing: 'Harf aralığı',
    sectionGap: 'Bölüm aralığı',
    justify: 'Özeti iki yana yasla',
    skillStyle: 'Yetenek göstergesi',
    skillStyles: { '': 'Şablon', bar: 'Çubuk', dots: 'Nokta', chips: 'Rozet', text: 'Metin', ring: 'Halka' },
    bulletStyle: 'Madde işareti',
    bulletStyles: { dot: 'Nokta', square: 'Kare', dash: 'Çizgi', arrow: 'Ok', check: 'Onay' },
    photoShape: 'Fotoğraf çerçevesi',
    photoShapes: { '': 'Şablon', circle: 'Yuvarlak', square: 'Kare', rounded: 'Yumuşak köşe' },
    photoSize: 'Fotoğraf boyutu',
    photoNone: 'Bu şablon fotoğrafsız tasarlandı; çerçeve seçersen yine de eklenir.',
    font: 'Yazı tipi',
    fonts: { sans: 'Modern (Inter)', serif: 'Klasik (Serif)', mono: 'Teknik (Mono)', display: 'İddialı (Grotesk)' },
    fontScale: 'Yazı boyutu',
    lineHeight: 'Satır aralığı',
    margin: 'Sayfa boşluğu',
    paper: 'Kâğıt',
    photoToggle: 'Fotoğrafı göster',
    iconsToggle: 'İletişim ikonlarını göster',
    reset: 'Varsayılanlara dön',
    orderTitle: 'Bölüm sırası ve görünürlük',
    orderHint: 'Sürükleyerek ya da okları kullanarak sırala. Göz simgesi bölümü gizler, sayfa simgesi bölümü yeni sayfada başlatır.',
    pageBreakOn: 'Yeni sayfada başlat',
    pageBreakOff: 'Sayfa başını kaldır',
    rename: 'Başlığı değiştir',
    show: 'Göster',
    hide: 'Gizle',
    emptyBadge: 'boş',
    changeTemplate: 'Şablonu değiştir',
    zoom: 'Yakınlaştırma',
    fit: 'Sığdır',
  },

  exportStep: {
    title: 'CV’n hazır',
    desc: 'PDF çıktısı tarayıcının kendi yazdırma motoruyla alınır: metin seçilebilir, vektörel ve ücretsizdir.',
    download: 'PDF olarak indir',
    preparing: 'Çıktı hazırlanıyor…',
    fileName: 'Dosya adı',
    tipsTitle: 'Kusursuz çıktı için',
    tips: [
      'Açılan pencerede hedef olarak “PDF olarak kaydet” seçili olmalı.',
      'Kenar boşluğu “Yok”, ölçek %100 olarak bırakılmalı.',
      '“Arka plan grafikleri” seçeneği işaretli olmalı — renkli bantlar ve yan sütunlar bu sayede basılır.',
      'Telefonda: Paylaş → Yazdır → parmakla büyüt → PDF olarak kaydet.',
    ],
    pages: (n: number) => `${n} sayfa`,
    backupTitle: 'Yedek',
    backupDesc: 'Bilgilerini JSON olarak indir; sonra istediğin an geri yükleyip farklı bir şablonla yeniden üret.',
    startOver: 'Yeni CV oluştur',
    startOverConfirm: 'Mevcut CV silinip sıfırdan başlanacak. Devam edilsin mi?',
    templateLabel: 'Şablon',
  },

  sections: {
    summary: 'Profil',
    experience: 'Deneyim',
    education: 'Eğitim',
    skills: 'Yetenekler',
    languages: 'Diller',
    projects: 'Projeler',
    certificates: 'Sertifikalar',
    awards: 'Ödüller',
    interests: 'İlgi Alanları',
    references: 'Referanslar',
  } as Record<SectionKey, string>,

  categories: {
    corporate: 'Kurumsal',
    modern: 'Modern',
    minimal: 'Minimal',
    creative: 'Yaratıcı',
    technical: 'Teknik',
    academic: 'Akademik',
  } as Record<TplCategory, string>,

  f: {
    identity: 'Kimlik',
    contact: 'İletişim',
    fullName: 'Ad Soyad',
    jobTitle: 'Unvan',
    photo: 'Fotoğraf',
    summary: 'Kısa özet',
    email: 'E-posta',
    phone: 'Telefon',
    location: 'Konum',
    website: 'Web sitesi',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    birthDate: 'Doğum tarihi',
    nationality: 'Uyruk',
    drivingLicense: 'Ehliyet',
    military: 'Askerlik',
    role: 'Pozisyon',
    company: 'Şirket',
    start: 'Başlangıç',
    end: 'Bitiş',
    achievements: 'Öne çıkanlar',
    degree: 'Bölüm / Derece',
    school: 'Okul',
    grade: 'Not ortalaması',
    skillName: 'Yetenek',
    group: 'Grup',
    level: 'Seviye',
    langName: 'Dil',
    langLevel: 'Seviye (metin)',
    projectName: 'Proje adı',
    link: 'Bağlantı',
    tech: 'Teknolojiler',
    certName: 'Sertifika',
    issuer: 'Kurum',
    date: 'Tarih',
    awardName: 'Ödül',
    refName: 'Ad Soyad',
    refContact: 'İletişim',
    description: 'Açıklama',
  },

  present: 'Devam ediyor',
  a11yPreview: 'CV önizlemesi',
}

const EN: typeof TR = {
  appTitle: 'CV Studio',
  appSub: 'Pick a template, fill in your details, fine-tune it, download a PDF — all in your browser.',
  freeBadge: 'Free · No sign-up · Your data stays on your device',

  loader: {
    brand: 'CV Studio',
    lines: [
      'Preparing the template library',
      'Loading typography and colour palettes',
      'Scaling the page layout',
      'Opening your workspace',
    ],
    ready: 'Ready',
  },

  steps: [
    { title: 'Template', sub: '' },
    { title: 'Details', sub: 'Fill the fields' },
    { title: 'Refine', sub: 'Fine-tune' },
    { title: 'Download', sub: 'PDF output' },
  ],
  stepOf: (i: number, n: number) => `Step ${i} of ${n}`,
  cancel: 'Cancel',
  next: 'Continue',
  back: 'Back',
  finish: 'Go to PDF step',

  gallery: {
    title: 'Start with a template',
    desc: (n: number) =>
      `${n} professional layouts, named after districts of Elazığ, Malatya and Kastamonu. Whatever you pick, you can still change its colour, typography and section order in the next steps.`,
    search: 'Search templates…',
    all: 'All',
    empty: 'No template matches this filter.',
    use: 'Use this template',
    continue: 'Continue',
    selected: 'Selected',
    select: 'Select',
    preview: 'Enlarge',
    previewTitle: 'Template preview',
    count: (n: number) => `${n} templates`,
    liveNote: 'Card previews are the real template, scaled down.',
  },

  form: {
    title: 'Fill in your details',
    desc: 'Sections you leave empty stay off the CV. Everything updates in the preview as you type.',
    previewTab: 'Preview',
    formTab: 'Form',
    fillSample: 'Fill with sample data',
    clearAll: 'Clear everything',
    clearConfirm: 'Every detail you entered will be deleted. Continue?',
    exportJson: 'Back up (JSON)',
    importJson: 'Load a backup',
    importError: 'Could not read the file — it is not a valid CV backup.',
    add: 'Add',
    remove: 'Delete',
    moveUp: 'Move up',
    moveDown: 'Move down',
    empty: 'Nothing here yet.',
    photoAdd: 'Upload a photo',
    photoChange: 'Change',
    photoRemove: 'Remove',
    photoHint: 'JPG/PNG · resized to 480px in the browser, never uploaded.',
    photoError: 'Could not read the image.',
    bulletsHint: 'Each line becomes a bullet.',
    interestsHint: 'Comma separated: Chess, Running, Photography',
    current: 'Ongoing',
    levelLabel: (n: number) => ['—', 'Beginner', 'Basic', 'Good', 'Advanced', 'Expert'][n] ?? '—',
    required: 'Optional, but it makes the CV stronger.',
    savedAt: (t: string) => `Saved automatically · ${t}`,
  },

  editor: {
    title: 'Fine-tune it',
    desc: 'Change colour, typography, density and section order. Every change lands in the preview instantly.',
    tabDesign: 'Design',
    tabSections: 'Sections',
    tabTemplate: 'Template',
    accent: 'Accent colour',
    accentReset: 'Back to template colour',
    groupColor: 'Colour and tone',
    groupType: 'Typography',
    groupLayout: 'Layout',
    groupPhoto: 'Photo',
    groupDetails: 'Details',
    rail: 'Sidebar colour',
    railReset: 'Template tone',
    paperTint: 'Paper tone',
    paperTints: { template: 'Template', white: 'White', cream: 'Cream', gray: 'Grey' },
    inkTone: 'Text tone',
    inkTones: { template: 'Template', slate: 'Slate', black: 'Black', navy: 'Navy', warm: 'Warm' },
    headingFont: 'Heading typeface',
    headingScale: 'Heading size',
    letterSpacing: 'Letter spacing',
    sectionGap: 'Section spacing',
    justify: 'Justify the summary',
    skillStyle: 'Skill meter',
    skillStyles: { '': 'Template', bar: 'Bar', dots: 'Dots', chips: 'Chips', text: 'Text', ring: 'Ring' },
    bulletStyle: 'Bullet mark',
    bulletStyles: { dot: 'Dot', square: 'Square', dash: 'Dash', arrow: 'Arrow', check: 'Check' },
    photoShape: 'Photo frame',
    photoShapes: { '': 'Template', circle: 'Circle', square: 'Square', rounded: 'Rounded' },
    photoSize: 'Photo size',
    photoNone: 'This template was drawn without a photo; picking a frame adds one anyway.',
    font: 'Typeface',
    fonts: { sans: 'Modern (Inter)', serif: 'Classic (Serif)', mono: 'Technical (Mono)', display: 'Bold (Grotesk)' },
    fontScale: 'Font size',
    lineHeight: 'Line height',
    margin: 'Page margin',
    paper: 'Paper',
    photoToggle: 'Show the photo',
    iconsToggle: 'Show contact icons',
    reset: 'Reset to defaults',
    orderTitle: 'Section order and visibility',
    orderHint: 'Drag, or use the arrows, to reorder. The eye icon hides a section; the page icon starts it on a new page.',
    pageBreakOn: 'Start on a new page',
    pageBreakOff: 'Remove the page break',
    rename: 'Rename heading',
    show: 'Show',
    hide: 'Hide',
    emptyBadge: 'empty',
    changeTemplate: 'Change template',
    zoom: 'Zoom',
    fit: 'Fit',
  },

  exportStep: {
    title: 'Your CV is ready',
    desc: 'The PDF comes from your browser’s own print engine: selectable text, vector output, free.',
    download: 'Download as PDF',
    preparing: 'Preparing the output…',
    fileName: 'File name',
    tipsTitle: 'For a flawless output',
    tips: [
      'In the dialog that opens, the destination must be “Save as PDF”.',
      'Leave margins on “None” and the scale at 100%.',
      'Tick “Background graphics” — that is what prints the colour bands and sidebars.',
      'On a phone: Share → Print → pinch to zoom → Save as PDF.',
    ],
    pages: (n: number) => `${n} page${n === 1 ? '' : 's'}`,
    backupTitle: 'Backup',
    backupDesc: 'Download your details as JSON, then load them back any time and rebuild with another template.',
    startOver: 'Create a new CV',
    startOverConfirm: 'The current CV will be deleted and you will start over. Continue?',
    templateLabel: 'Template',
  },

  sections: {
    summary: 'Profile',
    experience: 'Experience',
    education: 'Education',
    skills: 'Skills',
    languages: 'Languages',
    projects: 'Projects',
    certificates: 'Certificates',
    awards: 'Awards',
    interests: 'Interests',
    references: 'References',
  },

  categories: {
    corporate: 'Corporate',
    modern: 'Modern',
    minimal: 'Minimal',
    creative: 'Creative',
    technical: 'Technical',
    academic: 'Academic',
  },

  f: {
    identity: 'Identity',
    contact: 'Contact',
    fullName: 'Full name',
    jobTitle: 'Job title',
    photo: 'Photo',
    summary: 'Short summary',
    email: 'Email',
    phone: 'Phone',
    location: 'Location',
    website: 'Website',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    birthDate: 'Date of birth',
    nationality: 'Nationality',
    drivingLicense: 'Driving licence',
    military: 'Military service',
    role: 'Role',
    company: 'Company',
    start: 'Start',
    end: 'End',
    achievements: 'Highlights',
    degree: 'Programme / Degree',
    school: 'Institution',
    grade: 'GPA',
    skillName: 'Skill',
    group: 'Group',
    level: 'Level',
    langName: 'Language',
    langLevel: 'Level (text)',
    projectName: 'Project name',
    link: 'Link',
    tech: 'Technologies',
    certName: 'Certificate',
    issuer: 'Issuer',
    date: 'Date',
    awardName: 'Award',
    refName: 'Full name',
    refContact: 'Contact',
    description: 'Description',
  },

  present: 'Present',
  a11yPreview: 'CV preview',
}

export type CvText = typeof TR

export function cvText(lang: Lang): CvText {
  return lang === 'en' ? EN : TR
}
