// ATS arayüz metinleri — TR (varsayılan) ve EN.
// Skor motorunun ürettiği başlık/açıklamalar zaten yerelleştirilmiş gelir (lib/ats/analyze.ts);
// burada yalnızca rapor ekranı, iş ilanı paneli ve yükleme sayfasının kabuk metinleri durur.
import type { Lang } from '@/lib/i18n/config'
import type { AtsCategoryKey, AtsParseErrorCode, AtsStatus, ResumeSectionKind } from './types'

/** Skor motorunun parse edilebilirlik tavanları (lib/ats/analyze.ts ile aynı eşikler). */
export const ATS_SCORE_CAPS = { unreadable: 20, severe: 64, single: 79 } as const

const TR = {
  score: 'ATS skoru',
  outOf: '/ 100',
  heroSub: {
    builder: 'Bu skor, seçtiğin şablonun gerçek yerleşimiyle indireceğin PDF’in bir ATS tarafından nasıl okunacağını ölçer.',
    upload: 'Dosyan, işe alım sistemlerinin kullandığı kurallarla tarandı. Aşağıda neyin işe yaradığını ve neyin puan kaybettirdiğini görebilirsin.',
  },
  stats: {
    sections: 'Bölüm',
    bullets: 'Madde',
    quantified: 'Ölçülebilir',
    pages: 'Sayfa',
    years: 'Deneyim',
    yearsValue: (n: number) => `${n} yıl`,
  },
  notMeasurable: 'Ölçülemedi',
  notMeasurableNote: 'Bazı yerleşim sinyalleri bu dosya türünde ölçülemedi; bu kontroller puan kırmadı.',

  categoriesTitle: 'Kategori dağılımı',
  categoriesDesc: 'Beş kategori, genel skora ağırlığı oranında katkı verir.',
  noJob: 'İlan eklenmedi',
  noJobHint: 'Ağırlığı diğer kategorilere dağıtıldı',
  noJobPartial: 'İlan eklenmedi · eşleşme puanı ilan eklenince hesaplanır',
  noSoftInPosting: 'İlanda yok',
  noSoftInPostingHint: 'İlanda kişisel yetkinlik geçmediği için puanlanmadı',
  /** Motor etiket göndermezse kullanılan kategori adları (yükleme sayfasının tanıtımı da bunları kullanır). */
  categoryNames: {
    formatting: 'Biçim & ATS uyumu',
    searchability: 'Aranabilirlik',
    hardSkills: 'Hard skills',
    softSkills: 'Soft skills',
    recruiterTips: 'İşe alımcı ipuçları',
  } as Record<AtsCategoryKey, string>,
  categoryInfo: {
    formatting: 'Metin okunabilirliği, tek kolon, tablo/metin kutusu/görsel/ikon, standart font, punto, kenar boşluğu, header/footer.',
    searchability: 'İletişim bilgileri, özet, standart bölüm başlıkları, unvan eşleşmesi, tarih biçimi, eğitim ve ters kronolojik sıra.',
    hardSkills: 'İlandaki teknik/mesleki anahtar kelimeler; deneyim maddelerinde bağlamıyla kullanım ve kısaltmaların açılımı.',
    softSkills: 'İlandaki kişisel yetkinlikler (iletişim, liderlik, problem çözme…) ve bunların somut örneklerle gösterilmesi.',
    recruiterTips: 'Ölçülebilir sonuçlar, eylem fiilleri, madde yapısı, klişe ifadeler, ton ve uzunluk.',
  } as Record<AtsCategoryKey, string>,

  method: {
    title: 'Nasıl puanlıyoruz?',
    summary: 'Jobscan / Resume Worded yapısı + katı ATS biçim kuralları',
    intro:
      'Skor, yaygın kabul gören CV tarama araçlarının (Jobscan, Resume Worded) beş kategorili yapısını izler; buna tek kolon, standart font ve başlık gibi katı ATS biçim kuralları ile 20 maddelik çıktı kontrol listesi eklenir. Her kural bir ağırlık taşır; kategori puanı, kurallardan kazanılan puanların toplamıdır.',
    weightsTitle: (provided: boolean): string => (provided ? 'Bu rapordaki ağırlıklar · ilan eklendi' : 'Bu rapordaki ağırlıklar · ilan yok'),
    jobNote: {
      with: 'İlan eklendiği için Hard skills ve Soft skills eşleşmesi puanlandı. İlan kaldırılırsa bu iki kategorinin ağırlığı diğer kategorilere oransal olarak dağıtılır.',
      without: 'İlan eklenmediği için Hard skills ve Soft skills eşleşmesi puanlanmadı; ağırlıkları diğer kategorilere oransal olarak dağıtıldı. İlan eklediğinde bu iki kategori devreye girer.',
    },
    capsTitle: 'Parse edilebilirlik tavanları',
    capsDesc: 'İçerik ne kadar güçlü olursa olsun, ATS’nin doğru okuyamadığı bir belge yüksek skor alamaz:',
    caps: [
      { n: ATS_SCORE_CAPS.unreadable, d: 'Seçilebilir metin yok (taranmış/görsel PDF)' },
      { n: ATS_SCORE_CAPS.severe, d: 'İki veya daha fazla kritik yerleşim hatası (çok kolon, tablo, metin kutusu, grafik…)' },
      { n: ATS_SCORE_CAPS.single, d: 'Tek bir kritik yerleşim hatası' },
    ],
    capLabel: (n: number) => `en fazla ${n}`,
    gradesTitle: 'Not aralıkları',
    grades: [
      { k: 'excellent', r: '85–100', l: 'Mükemmel' },
      { k: 'good', r: '70–84', l: 'İyi' },
      { k: 'fair', r: '50–69', l: 'Geliştirilmeli' },
      { k: 'poor', r: '0–49', l: 'Zayıf' },
    ] as { k: 'excellent' | 'good' | 'fair' | 'poor'; r: string; l: string }[],
    weight: 'Ağırlık',
    pct: (n: number) => `%${n}`,
  },

  topFixesTitle: 'Önce bunları düzelt',
  topFixesDesc: 'Puana en çok etki eden iyileştirmeler, kazanç sırasıyla.',
  topFixesEmpty: 'Kritik bir sorun yok — CV’n ATS açısından sağlam görünüyor.',
  gain: (n: number) => `+${n} puan`,
  fix: 'Düzelt',
  howToFix: 'Nasıl düzeltilir',

  checksTitle: 'Tüm kontroller',
  checksDesc: (n: number) => `${n} kural beş kategoride tek tek değerlendirildi.`,
  filters: { all: 'Tümü', fail: 'Hatalar', warn: 'Uyarılar', pass: 'Geçenler' },
  filterEmpty: 'Bu filtrede kontrol yok.',
  status: { pass: 'Geçti', warn: 'Uyarı', fail: 'Hata', info: 'Ölçülemedi' } as Record<AtsStatus, string>,
  points: (earned: number, weight: number) => `${earned}/${weight}`,
  expand: 'Ayrıntıyı göster',
  collapse: 'Ayrıntıyı gizle',

  checklistTitle: 'ATS Çıktı Kontrol Listesi',
  checklistDesc: 'İşe alım sistemlerinin beklediği 20 temel kural.',
  checklistCount: (ok: number, n: number) => `${ok}/${n} tamam`,
  checklistEmpty: 'Kontrol listesi bu rapor için hazırlanamadı.',

  keywordsTitle: 'Anahtar kelime eşleşmesi',
  keywordsDesc: 'İlandaki hard ve soft skill’lerin CV’nde nasıl karşılandığı.',
  keywordsEmptyTitle: 'İş ilanı eklenmedi',
  keywordsEmptyDesc: 'Başvuracağın ilanın metnini eklediğinde hard/soft skill eşleşmesini, eksik anahtar kelimeleri ve unvan uyumunu burada göreceksin.',
  keywordsEmptyCta: 'İş ilanını ekle',
  matchRate: 'Eşleşme',
  hardTitle: 'Hard skills',
  hardDesc: 'Teknik ve mesleki yetkinlikler: araçlar, teknolojiler, yöntemler, sertifikalar.',
  softTitle: 'Soft skills',
  softDesc: 'Kişisel yetkinlikler: iletişim, liderlik, takım çalışması, problem çözme…',
  softNone: 'İlanda belirgin bir soft skill bulunamadı.',
  hardNone: 'İlanda belirgin bir hard skill bulunamadı.',
  matched: (n: number) => `Eşleşen (${n})`,
  missing: (n: number) => `Eksik (${n})`,
  inExperience: 'Deneyimde geçiyor',
  onlySkills: 'Yalnızca yetenekler listesinde',
  importance: { high: 'Kritik', medium: 'Önemli', low: 'Destekleyici' },
  signalsTitle: 'İçerik sinyalleri',
  signalsDesc: 'İlandan bağımsız olarak metinde bulunan sorunlar.',
  skillsOnlyTitle: 'Bağlamsız yetenekler',
  skillsOnlyDesc: 'Bu teknolojiler yalnızca yetenekler listesinde. En az birini bir deneyim maddesinde kullan.',
  stuffingTitle: 'Aşırı tekrar şüphesi',
  stuffingDesc: 'Bu terimler doğal olmayan sıklıkta geçiyor; ATS ve insan okuyucu için anahtar kelime doldurma gibi görünebilir.',
  buzzwordsTitle: 'Klişe ifadeler',
  buzzwordsDesc: 'İşe alımcılar bu kalıpları boş bulur. Yerine somut bir örnek ya da ölçülebilir bir sonuç yaz.',
  titleMatch: 'Unvan uyumu',
  titleMatchYes: 'CV unvanın ilandaki pozisyonla örtüşüyor.',
  titleMatchNo: 'CV unvanın ilandaki pozisyonla örtüşmüyor — hedef unvanı başlığa ekle.',
  titleMatchNone: 'Karşılaştırılacak ilan unvanı bulunamadı.',
  acronymsTitle: 'Açılımı verilmeyen kısaltmalar',
  acronymsDesc: 'İlk kullanımda açılımını yaz: “Continuous Integration (CI)”.',
  noneMissing: 'Eksik anahtar kelime yok.',

  parserTitle: 'ATS’nin gördüğü metin',
  parserDesc: 'Bir ATS’nin CV’nden okuyacağı düz metin, doğal okuma sırasıyla. Vurgulananlar bölüm başlığı olarak tanındı.',
  parserFields: 'Tespit edilen alanlar',
  parserEmpty: 'Okunabilir metin bulunamadı.',
  copy: 'Metni kopyala',
  copied: 'Kopyalandı',
  showAll: 'Tamamını göster',
  showLess: 'Daralt',
  found: 'Bulundu',
  notFound: 'Yok',
  fields: {
    name: 'Ad Soyad',
    title: 'Unvan',
    email: 'E-posta',
    phone: 'Telefon',
    location: 'Konum',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Web sitesi',
  },
  sectionKinds: {
    contact: 'iletişim',
    summary: 'özet',
    experience: 'deneyim',
    education: 'eğitim',
    skills: 'yetenekler',
    projects: 'projeler',
    certifications: 'sertifikalar',
    languages: 'diller',
    awards: 'ödüller',
    interests: 'ilgi alanları',
    references: 'referanslar',
    other: 'diğer',
  } as Record<ResumeSectionKind, string>,
  nonStandard: 'standart dışı',

  job: {
    title: 'İş ilanıyla eşleştir',
    desc: 'İlan metnini yapıştır; hard/soft skill eşleşmesini, eksik anahtar kelimeleri ve unvan uyumunu hesaplayalım.',
    cta: 'İş ilanını ekle',
    ctaSub: 'Hard & soft skill eşleşmesini gör',
    targetTitle: 'Hedef pozisyon',
    targetPlaceholder: 'ör. Senior Backend Developer',
    posting: 'İlan metni',
    postingPlaceholder: 'İlanın tamamını buraya yapıştır: sorumluluklar, aranan nitelikler, teknolojiler…',
    helper: 'İlan metni yalnızca bu cihazda işlenir. Anahtar kelimeleri deneyim maddelerinde doğal bir bağlamda kullan; listeyi tekrar etme.',
    chars: (n: number) => `${n.toLocaleString('tr-TR')} karakter`,
    clear: 'Temizle',
    collapse: 'Gizle',
  },

  badge: 'ATS',
  badgeTitle: (n: number, family: string, name: string) => `ATS skoru ${n}/100 · ${name} (${family}) — ayrıntılar için tıkla`,

  template: {
    computedFor: 'Skor bu şablona göre hesaplandı',
    family: { ats: 'ATS uyumlu', design: 'Görsel tasarım' },
    change: 'Şablonu değiştir',
  },

  compare: {
    eyebrow: 'Şablon karşılaştırması',
    title: 'Aynı CV, ATS uyumlu şablonla daha yüksek puan alır',
    desc: 'Aynı içerik ve aynı iş ilanıyla yalnızca yerleşim değiştirildi.',
    current: 'Görsel şablon',
    target: (name: string) => `ATS uyumlu ${name}`,
    delta: (n: number) => (n > 0 ? `+${n}` : String(n)),
    whyTitle: 'Bu şablonda puanı düşürenler',
    whyPts: (n: number) => `−${n}`,
    whyEmpty: 'Puan farkı küçük kurallardan geliyor; ayrıntılar aşağıdaki kontrollerde.',
    switchCta: 'ATS uyumlu şablona geç',
    browseCta: 'Diğer ATS şablonlarını gör',
    note: 'Görsel şablonlar insan okuyucu için etkileyicidir; ATS kullanan şirketlere başvururken ATS uyumlu şablonu indir. Word (DOCX) çıktısı her durumda ATS uyumludur.',
  },

  builder: {
    analyzeLink: 'Mevcut CV’ni analiz et',
    downloadTitle: 'İndir',
    downloadDesc: {
      ats: 'Tüm çıktılar aynı tek kolonlu, metin tabanlı içerikten üretilir.',
      design: 'PDF seçili görsel şablonun görünümünü taşır; DOCX ve TXT çıktıları ATS uyumlu tek kolon düzendedir.',
    },
    pdf: 'PDF',
    pdfSub: 'Yazdırma motoru · önerilen',
    docx: 'DOCX',
    docxSub: 'Word · düzenlenebilir',
    docxNote: 'Word çıktısı ATS uyumlu tek kolon düzendedir',
    txt: 'TXT',
    txtSub: 'Düz metin · form alanları için',
    docxError: 'Word dosyası oluşturulamadı.',
    livePreview: 'Canlı önizleme',
    reportError: 'ATS raporu şu an hesaplanamadı. İçeriğini düzenleyip tekrar dene.',
    emptyTitle: 'CV’n henüz boş',
    emptyDesc: 'Skor hesaplamak için önce bilgilerini gir.',
    emptyCta: 'Bilgileri doldur',
  },

  analyzer: {
    eyebrow: 'Ücretsiz ATS analizi',
    title: 'CV’n bir ATS’den geçer mi?',
    titleAccent: 'Saniyeler içinde öğren.',
    sub: 'PDF, DOCX ya da TXT dosyanı bırak. Yaygın kabul gören CV skorlama modeli ve katı ATS kurallarıyla puanlayalım; neyin eksik olduğunu ve nasıl düzelteceğini gösterelim.',
    privacy: 'Dosyan cihazından çıkmaz · Kayıt yok',
    dropTitle: 'CV’ni buraya sürükle',
    dropOr: 'ya da',
    dropBrowse: 'dosya seç',
    dropActive: 'Bırak, analiz başlasın',
    dropMeta: 'PDF, DOCX, TXT · en fazla 10 MB',
    dropPaste: 'Panodan dosya yapıştırmak da olur (⌘/Ctrl + V).',
    selected: 'Seçilen dosya',
    remove: 'Kaldır',
    analyze: 'Analiz et',
    optionalJob: 'İsteğe bağlı: iş ilanı ekle',
    steps: [
      'Dosya okunuyor',
      'Metin katmanı çıkarılıyor',
      'Yerleşim sinyalleri inceleniyor',
      'Bölümler ayrıştırılıyor',
      'Hard & soft skill’ler eşleştiriliyor',
      'Beş kategoride skor hesaplanıyor',
    ],
    analyzing: 'Analiz ediliyor',
    reportFor: 'Analiz edilen dosya',
    pages: (n: number) => `${n} sayfa`,
    uploadAnother: 'Başka CV yükle',
    recalc: 'İlanı güncelle ve yeniden hesapla',
    recalcDone: 'Skor güncellendi',
    rebuildEyebrow: 'Tek tıkla',
    rebuildTitle: 'Bu CV’yi ATS uyumlu şablonla yeniden oluştur',
    rebuildDesc: (n: number) =>
      `Okunan bilgileri CV Stüdyosu’na ATS uyumlu Çankaya şablonuyla aktaralım. ${n} ATS uyumlu şablondan dilediğine geç, eksikleri tamamla, PDF ya da DOCX olarak indir.`,
    rebuildCta: 'CV Stüdyosu’nda aç',
    overwriteTitle: 'Mevcut CV’nin üzerine yazılsın mı?',
    overwriteText: 'CV Stüdyosu’nda kayıtlı bir CV var. Yüklediğin CV’nin bilgileri onun yerine geçecek.',
    overwriteConfirm: 'Üzerine yaz',
    cancel: 'Vazgeç',
    errors: {
      unsupported: 'Yalnızca PDF, DOCX ve TXT desteklenir. .doc dosyasını Word’de “Farklı Kaydet → DOCX” ile kaydedip tekrar dene.',
      encrypted: 'Bu dosya parola korumalı. Korumayı kaldırıp yeniden yükle — ATS’ler de şifreli dosyaları okuyamaz.',
      'too-large': 'Dosya 10 MB sınırını aşıyor. Görselleri kaldırıp ya da sıkıştırıp yeniden dene.',
      empty: 'Dosyada okunabilir metin bulunamadı. Taranmış (görsel) bir PDF olabilir; ATS’ler bu tür dosyaları okuyamaz.',
      corrupt: 'Dosya açılamadı; bozuk ya da beklenmedik bir biçimde olabilir. Farklı bir dışa aktarımla tekrar dene.',
    } as Record<AtsParseErrorCode, string>,
    errorTitle: 'Dosya analiz edilemedi',
    howTitle: 'Nasıl puanlıyoruz?',
    howDesc:
      'ATS’ler CV’ni önce düz metne çevirir, sonra alanlara ayırır. Skor, Jobscan / Resume Worded’ın beş kategorili yapısını ve katı ATS biçim kurallarını izler; ağırlıklar iş ilanı eklenip eklenmemesine göre raporda gösterilir.',
    howCaps: (a: number, b: number) =>
      `Okunamayan belgeler için tavan uygulanır: seçilebilir metin yoksa en fazla ${a}, birden çok kritik yerleşim hatasında en fazla ${b} puan.`,
  },
}

export type AtsText = typeof TR

const EN: AtsText = {
  score: 'ATS score',
  outOf: '/ 100',
  heroSub: {
    builder: 'This score measures how an ATS will read the PDF you download, using the real layout of the template you selected.',
    upload: 'Your file was scanned with the rules hiring systems use. Below you can see what works and what costs you points.',
  },
  stats: {
    sections: 'Sections',
    bullets: 'Bullets',
    quantified: 'Quantified',
    pages: 'Pages',
    years: 'Experience',
    yearsValue: (n: number) => `${n} yr${n === 1 ? '' : 's'}`,
  },
  notMeasurable: 'Not measurable',
  notMeasurableNote: 'Some layout signals could not be measured for this file type; those checks did not cost points.',

  categoriesTitle: 'Category breakdown',
  categoriesDesc: 'Five categories contribute to the overall score by their weight.',
  noJob: 'No job posting',
  noJobHint: 'Its weight is spread across the other categories',
  noJobPartial: 'No job posting · matching is scored once you add one',
  noSoftInPosting: 'Not in posting',
  noSoftInPostingHint: 'The posting lists no soft skills, so this was not scored',
  categoryNames: {
    formatting: 'Formatting & ATS fit',
    searchability: 'Searchability',
    hardSkills: 'Hard skills',
    softSkills: 'Soft skills',
    recruiterTips: 'Recruiter tips',
  },
  categoryInfo: {
    formatting: 'Text readability, single column, tables/text boxes/images/icons, standard fonts, font sizes, margins, header/footer.',
    searchability: 'Contact details, summary, standard section headings, job title match, date format, education and reverse-chronological order.',
    hardSkills: 'Technical and professional keywords from the posting, used in context inside experience bullets, with acronyms spelled out.',
    softSkills: 'Interpersonal skills from the posting (communication, leadership, problem solving…) backed by concrete examples.',
    recruiterTips: 'Measurable results, action verbs, bullet structure, buzzwords, tone and length.',
  },

  method: {
    title: 'How do we score?',
    summary: 'Jobscan / Resume Worded structure + strict ATS formatting rules',
    intro:
      'The score follows the five-category structure of widely used resume scanners (Jobscan, Resume Worded), plus strict ATS formatting rules such as single column, standard fonts and headings, and a 20-item output checklist. Every rule carries a weight; a category score is the sum of the points earned from its rules.',
    weightsTitle: (provided: boolean) => (provided ? 'Weights in this report · with job posting' : 'Weights in this report · no job posting'),
    jobNote: {
      with: 'A job posting was added, so hard and soft skill matching was scored. Without a posting, the weight of these two categories is spread proportionally across the others.',
      without: 'No job posting was added, so hard and soft skill matching was not scored; their weight was spread proportionally across the other categories. Add a posting to bring both categories into play.',
    },
    capsTitle: 'Parseability caps',
    capsDesc: 'No matter how strong the content is, a document an ATS cannot read correctly cannot score high:',
    caps: [
      { n: ATS_SCORE_CAPS.unreadable, d: 'No selectable text (scanned/image PDF)' },
      { n: ATS_SCORE_CAPS.severe, d: 'Two or more critical layout errors (multiple columns, tables, text boxes, graphics…)' },
      { n: ATS_SCORE_CAPS.single, d: 'A single critical layout error' },
    ],
    capLabel: (n: number) => `max ${n}`,
    gradesTitle: 'Grade bands',
    grades: [
      { k: 'excellent', r: '85–100', l: 'Excellent' },
      { k: 'good', r: '70–84', l: 'Good' },
      { k: 'fair', r: '50–69', l: 'Needs work' },
      { k: 'poor', r: '0–49', l: 'Weak' },
    ],
    weight: 'Weight',
    pct: (n: number) => `${n}%`,
  },

  topFixesTitle: 'Fix these first',
  topFixesDesc: 'The improvements with the biggest impact, ordered by points to gain.',
  topFixesEmpty: 'No critical issues — your CV looks solid for an ATS.',
  gain: (n: number) => `+${n} pts`,
  fix: 'Fix',
  howToFix: 'How to fix',

  checksTitle: 'All checks',
  checksDesc: (n: number) => `${n} rules evaluated one by one across five categories.`,
  filters: { all: 'All', fail: 'Errors', warn: 'Warnings', pass: 'Passed' },
  filterEmpty: 'No checks for this filter.',
  status: { pass: 'Passed', warn: 'Warning', fail: 'Error', info: 'Not measurable' },
  points: (earned: number, weight: number) => `${earned}/${weight}`,
  expand: 'Show details',
  collapse: 'Hide details',

  checklistTitle: 'ATS Output Checklist',
  checklistDesc: 'The 20 core rules hiring systems expect.',
  checklistCount: (ok: number, n: number) => `${ok}/${n} done`,
  checklistEmpty: 'The checklist could not be prepared for this report.',

  keywordsTitle: 'Keyword match',
  keywordsDesc: 'How the hard and soft skills in the posting are covered by your CV.',
  keywordsEmptyTitle: 'No job posting added',
  keywordsEmptyDesc: 'Add the text of the posting you are applying for to see hard/soft skill matching, missing keywords and title alignment here.',
  keywordsEmptyCta: 'Add a job posting',
  matchRate: 'Match',
  hardTitle: 'Hard skills',
  hardDesc: 'Technical and professional skills: tools, technologies, methods, certifications.',
  softTitle: 'Soft skills',
  softDesc: 'Interpersonal skills: communication, leadership, teamwork, problem solving…',
  softNone: 'No clear soft skills found in the posting.',
  hardNone: 'No clear hard skills found in the posting.',
  matched: (n: number) => `Matched (${n})`,
  missing: (n: number) => `Missing (${n})`,
  inExperience: 'Used in experience',
  onlySkills: 'Only in the skills list',
  importance: { high: 'Critical', medium: 'Important', low: 'Supporting' },
  signalsTitle: 'Content signals',
  signalsDesc: 'Issues found in the text regardless of the posting.',
  skillsOnlyTitle: 'Skills without context',
  skillsOnlyDesc: 'These technologies only appear in the skills list. Use at least one of them in an experience bullet.',
  stuffingTitle: 'Possible keyword stuffing',
  stuffingDesc: 'These terms repeat unnaturally often; to an ATS and a human reader it can look like stuffing.',
  buzzwordsTitle: 'Buzzwords',
  buzzwordsDesc: 'Recruiters read these phrases as filler. Replace them with a concrete example or a measurable result.',
  titleMatch: 'Title alignment',
  titleMatchYes: 'Your CV title matches the role in the posting.',
  titleMatchNo: 'Your CV title does not match the role in the posting — add the target title to your header.',
  titleMatchNone: 'No posting title to compare against.',
  acronymsTitle: 'Unexplained acronyms',
  acronymsDesc: 'Spell them out on first use: “Continuous Integration (CI)”.',
  noneMissing: 'No missing keywords.',

  parserTitle: 'What the ATS sees',
  parserDesc: 'The plain text an ATS will read from your CV, in natural reading order. Highlighted lines were recognised as section headings.',
  parserFields: 'Detected fields',
  parserEmpty: 'No readable text found.',
  copy: 'Copy text',
  copied: 'Copied',
  showAll: 'Show all',
  showLess: 'Collapse',
  found: 'Found',
  notFound: 'Missing',
  fields: {
    name: 'Full name',
    title: 'Title',
    email: 'Email',
    phone: 'Phone',
    location: 'Location',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    website: 'Website',
  },
  sectionKinds: {
    contact: 'contact',
    summary: 'summary',
    experience: 'experience',
    education: 'education',
    skills: 'skills',
    projects: 'projects',
    certifications: 'certifications',
    languages: 'languages',
    awards: 'awards',
    interests: 'interests',
    references: 'references',
    other: 'other',
  },
  nonStandard: 'non-standard',

  job: {
    title: 'Match a job posting',
    desc: 'Paste the posting; we will work out hard/soft skill matching, missing keywords and title alignment.',
    cta: 'Add a job posting',
    ctaSub: 'See your hard & soft skill match',
    targetTitle: 'Target role',
    targetPlaceholder: 'e.g. Senior Backend Developer',
    posting: 'Posting text',
    postingPlaceholder: 'Paste the whole posting here: responsibilities, requirements, technologies…',
    helper: 'The posting is processed on this device only. Use keywords naturally inside experience bullets; do not just repeat the list.',
    chars: (n: number) => `${n.toLocaleString('en-US')} characters`,
    clear: 'Clear',
    collapse: 'Hide',
  },

  badge: 'ATS',
  badgeTitle: (n: number, family: string, name: string) => `ATS score ${n}/100 · ${name} (${family}) — click for details`,

  template: {
    computedFor: 'Score calculated for this template',
    family: { ats: 'ATS-compliant', design: 'Visual design' },
    change: 'Change template',
  },

  compare: {
    eyebrow: 'Template comparison',
    title: 'The same CV scores higher with an ATS-compliant template',
    desc: 'Same content and the same job posting — only the layout changed.',
    current: 'Visual template',
    target: (name: string) => `ATS-compliant ${name}`,
    delta: (n: number) => (n > 0 ? `+${n}` : String(n)),
    whyTitle: 'What lowers the score with this template',
    whyPts: (n: number) => `−${n}`,
    whyEmpty: 'The gap comes from minor rules; see the checks below for details.',
    switchCta: 'Switch to the ATS-compliant template',
    browseCta: 'See other ATS templates',
    note: 'Visual templates impress human readers; when applying to companies that use an ATS, download the ATS-compliant template. The Word (DOCX) export is ATS-compliant either way.',
  },

  builder: {
    analyzeLink: 'Analyse an existing CV',
    downloadTitle: 'Download',
    downloadDesc: {
      ats: 'Every format is produced from the same single-column, text-based content.',
      design: 'The PDF keeps the look of the selected visual template; DOCX and TXT exports use an ATS-compliant single-column layout.',
    },
    pdf: 'PDF',
    pdfSub: 'Print engine · recommended',
    docx: 'DOCX',
    docxSub: 'Word · editable',
    docxNote: 'The Word export uses an ATS-compliant single-column layout',
    txt: 'TXT',
    txtSub: 'Plain text · for form fields',
    docxError: 'The Word file could not be created.',
    livePreview: 'Live preview',
    reportError: 'The ATS report could not be calculated right now. Edit your content and try again.',
    emptyTitle: 'Your CV is still empty',
    emptyDesc: 'Fill in your details first to calculate a score.',
    emptyCta: 'Fill in details',
  },

  analyzer: {
    eyebrow: 'Free ATS analysis',
    title: 'Will your CV get through an ATS?',
    titleAccent: 'Find out in seconds.',
    sub: 'Drop your PDF, DOCX or TXT file. We score it with the widely used resume scoring model and strict ATS rules, and show what is missing and how to fix it.',
    privacy: 'Your file never leaves your device · No sign-up',
    dropTitle: 'Drag your CV here',
    dropOr: 'or',
    dropBrowse: 'choose a file',
    dropActive: 'Drop it to start the analysis',
    dropMeta: 'PDF, DOCX, TXT · up to 10 MB',
    dropPaste: 'You can also paste a file from the clipboard (⌘/Ctrl + V).',
    selected: 'Selected file',
    remove: 'Remove',
    analyze: 'Analyse',
    optionalJob: 'Optional: add a job posting',
    steps: [
      'Reading the file',
      'Extracting the text layer',
      'Inspecting layout signals',
      'Parsing sections',
      'Matching hard & soft skills',
      'Scoring five categories',
    ],
    analyzing: 'Analysing',
    reportFor: 'Analysed file',
    pages: (n: number) => `${n} page${n === 1 ? '' : 's'}`,
    uploadAnother: 'Upload another CV',
    recalc: 'Update posting and recalculate',
    recalcDone: 'Score updated',
    rebuildEyebrow: 'One click',
    rebuildTitle: 'Rebuild this CV with an ATS-compliant template',
    rebuildDesc: (n: number) =>
      `We will move the extracted details into CV Studio with the ATS-compliant Çankaya template. Switch to any of the ${n} ATS-compliant templates, fill the gaps, download as PDF or DOCX.`,
    rebuildCta: 'Open in CV Studio',
    overwriteTitle: 'Overwrite your current CV?',
    overwriteText: 'There is a CV saved in CV Studio. The details from the uploaded CV will replace it.',
    overwriteConfirm: 'Overwrite',
    cancel: 'Cancel',
    errors: {
      unsupported: 'Only PDF, DOCX and TXT are supported. Save your .doc file as DOCX in Word (“Save As → DOCX”) and try again.',
      encrypted: 'This file is password protected. Remove the protection and upload again — ATSs cannot read encrypted files either.',
      'too-large': 'The file exceeds the 10 MB limit. Remove or compress images and try again.',
      empty: 'No readable text found. It may be a scanned (image) PDF; ATSs cannot read such files.',
      corrupt: 'The file could not be opened; it may be damaged or in an unexpected format. Try a different export.',
    },
    errorTitle: 'The file could not be analysed',
    howTitle: 'How do we score?',
    howDesc:
      'An ATS first turns your CV into plain text, then splits it into fields. The score follows the five-category structure of Jobscan / Resume Worded and strict ATS formatting rules; the report shows the weights with or without a job posting.',
    howCaps: (a: number, b: number) =>
      `Caps apply to unreadable documents: at most ${a} points with no selectable text, at most ${b} with several critical layout errors.`,
  },
}

export function atsText(lang: Lang): AtsText {
  return lang === 'en' ? EN : TR
}
