// AI Sunum Stüdyosu arayüz metinleri — TR (varsayılan) ve EN.
// Site genelindeki dil anahtarıyla (lib/i18n) birlikte döner.
// Not: SLAYTLARA basılan metinler burada değil; onlar sunumun kendi diline
// (presentation.language) göre lib/sunum/templates.ts ve outline.ts içinde üretilir.

import type { Lang } from '@/lib/i18n/config'
import type { CoachCode } from './coach'
import type { IssueCode } from './decide/quality'
import type {
  Audience,
  Depth,
  Framework,
  RefineAction,
  SlideType,
  SourceMode,
  Tone,
  Visual,
} from './types'

const TR = {
  appTitle: 'AI Sunum Stüdyosu',
  appSub:
    'Konuyu yaz ya da PDF/DOCX yükle; yapay zekâ içeriği ve akışı kurar, Slide Engine profesyonel tasarımı üretir. PPTX ve PDF olarak indir.',
  freeBadge: 'Ücretsiz · Yerel AI (Ollama) · Kayıt yok · Veriler cihazında kalır',

  /* --------------------------------- açılış --------------------------------- */
  hero: {
    eyebrow: 'AI Sunum Stüdyosu',
    title: 'Sunum hazırlamakla zaman kaybetme.',
    lead: 'Konunu anlat. Profesyonel sunumunu saniyeler içinde oluştur.',
    question: 'Ne hakkında bir sunum hazırlamak istiyorsun?',
    placeholder: 'Yapay zekânın eğitim sektöründeki etkileri',
    cta: 'Sunum Oluştur',
    or: 'veya',
    pdf: 'PDF Yükle',
    docx: 'Word Yükle',
    paste: 'Metin Yapıştır',
    chipsLabel: 'Hızlı başlangıç',
    chips: [
      { label: 'Üniversite projesi', topic: 'Bitirme projemin amacı, yöntemi ve sonuçları', audience: 'student' },
      { label: 'Yönetim sunumu', topic: 'Bu çeyreğin sonuçları ve gelecek çeyrek planı', audience: 'management' },
      { label: 'Teknik proje', topic: 'Yeni sistem mimarisi ve geçiş planı', audience: 'technical' },
      { label: 'Akademik sunum', topic: 'Araştırmanın yöntemi, bulguları ve katkısı', audience: 'academic' },
      { label: 'Satış sunumu', topic: 'Ürünün çözdüğü problem ve müşteriye kazandırdıkları', audience: 'customer' },
    ] as { label: string; topic: string; audience: Audience }[],
    how: 'Nasıl çalışır?',
    steps: [
      { title: 'Konuyu ver', body: 'Tek cümle yeterli. İstersen PDF ya da Word dosyanı yükle.' },
      { title: 'Üç seçim yap', body: 'Hedef kitle, süre ve tema. Gerisi varsayılanlarla gelir.' },
      { title: 'Sunumu al', body: 'Slaytlar oluşur, düzenlersin, PPTX ya da PDF indirirsin.' },
    ],
  },

  /* ------------------------------- kütüphane ------------------------------- */
  library: {
    title: 'Sunumlarım',
    empty: 'Henüz sunumun yok.',
    emptyHint: 'İlk sunumunu birkaç saniyede oluştur.',
    create: 'Yeni Sunum',
    open: 'Aç',
    duplicate: 'Kopyala',
    remove: 'Sil',
    removeConfirm: 'Bu sunum cihazından silinecek. Emin misin?',
    removed: 'Sunum silindi.',
    slides: (n: number) => `${n} slayt`,
    minutes: (n: number) => `${n} dk`,
    updated: 'Son düzenleme',
    aiBadge: 'AI taslağı',
    outlineBadge: 'Yerel taslak',
    copySuffix: '(kopya)',
  },

  /* --------------------------------- sihirbaz --------------------------------- */
  wizard: {
    steps: [
      { title: 'İçerik', sub: 'Ne anlatacaksın?' },
      { title: 'Ayarlar', sub: 'Süre, standart ve dil' },
      { title: 'Tasarım', sub: 'Tema seç' },
    ],
    stepOf: (i: number, n: number) => `Adım ${i} / ${n}`,
    next: 'Devam',
    back: 'Geri',
    create: 'Sunumu Oluştur',
    cancel: 'Vazgeç',
  },

  form: {
    topic: 'Ne anlatmak istiyorsun?',
    topicPlaceholder: 'Örn. Yapay zekânın eğitim sektöründeki kullanımı',
    topicHint: 'Tek cümlelik net bir konu en iyi sonucu verir.',
    description: 'Açıklama / kaynak metin',
    descriptionPlaceholder:
      'Sunumda geçmesini istediğin notları, verileri ya da metni buraya yapıştır (isteğe bağlı).',
    pasteToggle: 'Metin Yapıştır',
    upload: 'PDF / Word / metin yükle',
    dropHere: 'Dosyayı buraya bırak',
    dropHint: 'PDF, DOCX, TXT veya MD · en fazla 10 MB · dosya cihazından çıkmaz',
    analyzing: 'Dosya analiz ediliyor…',
    uploadDone: (name: string, chars: number) => `${name} · ${chars.toLocaleString('tr-TR')} karakter çıkarıldı`,
    uploadRemove: 'Kaldır',
    audience: 'Hedef kitle',
    duration: 'Sunum süresi',
    slideCount: 'Slayt sayısı',
    theme: 'Tasarım teması',
    language: 'Dil',
    tone: 'Sunum tipi',
    requirements: 'Sunumda olmasını istediklerin',
    requirementsHint:
      'Kendi cümlelerinle yaz; AI bunları yorumlayıp sunumun yapısına uygular. Boş bırakabilirsin.',
    requirementsPlaceholder:
      'Örn. Her bölümde gerçek bir örnek olsun. Rakamları grafikle göster. Sonunda kaynakça slaytı ekle.',
    requirementChips: [
      'Grafiklerle destekle',
      'Her bölümde örnek ver',
      'Süreç diyagramı ekle',
      'Sayılarla kanıtla',
      'Zaman çizelgesi ekle',
      'Kaynakça slaytı ekle',
      'Kısa ve öz olsun',
      'Hikâye anlatımı kullan',
    ],
    advanced: 'Gelişmiş ayarlar',
    depth: 'Üretim derinliği',
    minutesUnit: 'dakika',
    slidesUnit: 'slayt',
    aiConnection: 'AI bağlantısı',
  },

  /* -------------------------------- hatalar -------------------------------- */
  errors: {
    topicRequired: 'Bir konu yaz.',
    fileTooLarge: 'Dosya çok büyük (en fazla 10 MB).',
    fileType: 'Yalnızca PDF ve DOCX yükleyebilirsin.',
    fileEmpty: 'Dosyadan metin çıkarılamadı. Taranmış (görsel) bir PDF olabilir.',
    fileFailed: 'Dosya okunamadı.',
    notFound: 'Sunum bulunamadı.',
    notFoundHint: 'Bağlantı eskimiş olabilir ya da sunum bu cihazdan silinmiş.',
    saveQuota: 'Cihaz depolama alanı doldu. Eski sunumlardan birini sil.',
    generic: 'Sunum oluşturulamadı.',
    retry: 'Tekrar Dene',
    aiOffline: 'Yerel AI servisine ulaşılamadı.',
    openConnection: 'Bağlantıyı kur',
    aiOfflineDetail:
      'AI servisine ulaşılamadı. Sunum metninden yerel bir taslak çıkarıldı; bağlantıyı kurup yeniden üretebilirsin.',
    quotaDetail:
      'Ücretsiz modelin kotası doldu. Sunum metninden yerel bir taslak çıkarıldı; birkaç dakika sonra yeniden deneyebilir, başka bir ücretsiz modele geçebilir ya da kendi anahtarını girebilirsin.',
    refineFailed: 'AI komutu tamamlanamadı.',
    exportFailed: 'Dosya oluşturulamadı.',
  },

  /* ------------------------------ kurulum sihirbazı ------------------------------ */
  install: {
    title: 'Yerel model kurulumu',
    subtitle: 'Terminal bilmene gerek yok — adımları sırayla takip et.',
    open: 'Kurulum sihirbazı',
    close: 'Kapat',
    step1: '1. Ollama’yı kur',
    step2: '2. Tarayıcıya izin ver',
    step3: '3. Modeli indir',
    checking: 'Ollama aranıyor…',
    found: 'Ollama çalışıyor',
    notFound: 'Ollama bulunamadı',
    downloadApp: 'Ollama’yı indir',
    orCommand: 'ya da terminale yapıştır:',
    serveHint:
      'Kurduktan sonra Ollama’yı bu komutla başlat — tarayıcının bağlanabilmesi için gerekli.',
    waiting: 'Kurulumun tamamlanması bekleniyor…',
    waitingFor: (s: number) => `Bekleniyor · ${s} sn`,
    startService: 'Ollama’yı başlat',
    startingService: 'Ollama başlatılıyor…',
    serviceStarted: 'Ollama başlatıldı.',
    serviceNotInstalled: 'Ollama bu makinede bulunamadı. Önce 1. adımdaki kurulumu tamamla.',
    serviceFailed: 'Ollama başlatılamadı. Kurulumu tamamladıysan uygulamayı bir kez elle açmayı dene.',
    startWaiting: 'Kurdum, kontrol et',
    stopWaiting: 'Beklemeyi durdur',
    installed: 'Kurulu',
    install: 'Kur',
    installing: 'İndiriliyor…',
    cancel: 'İptal',
    pullStatus: {
      manifest: 'Model bilgisi alınıyor',
      downloading: 'İndiriliyor',
      verifying: 'Doğrulanıyor',
      writing: 'Yazılıyor',
      success: 'Tamamlandı',
    },
    done: (name: string) => `${name} kuruldu ve seçildi.`,
    errors: {
      unreachable: 'Ollama’ya ulaşılamadı. Aşağıdaki “Ollama’yı başlat” düğmesini dene.',
      'not-found': 'Bu model Ollama kütüphanesinde bulunamadı.',
      failed: 'İndirme tamamlanamadı.',
    },
    why: 'Neden yerel model?',
    whyBody:
      'Ücretsiz, sınırsız ve slayt metnin cihazından hiç çıkmıyor. Bir kez kurduktan sonra internet bağlantısı bile gerekmiyor.',
  },

  /* -------------------------------- bağlantı -------------------------------- */
  connection: {
    title: 'AI bağlantısı',
    connected: 'Bağlı',
    connecting: 'Bağlanılıyor…',
    offline: 'Bağlantı kurulamadı',
    autoConnected: 'Otomatik bağlanıldı',
    provider: 'Sağlayıcı',
    model: 'Model',
    apiKey: 'API anahtarı',
    apiKeyHint: 'Anahtar yalnızca bu tarayıcıda saklanır; bu sitenin sunucusuna gönderilmez.',
    apiKeyPlaceholder: 'sk-…',
    getKey: 'Anahtar al',
    baseUrl: 'Adres',
    baseUrlPlaceholder: 'https://api.ornek.com/v1',
    modelPlaceholder: 'model-adı',
    save: 'Bağlantıyı kaydet',
    saved: 'Bağlantı kaydedildi.',
    reset: 'Varsayılana dön',
    retry: 'Yeniden dene',
    needsKey: 'Bu sağlayıcı için bir API anahtarı gir.',
    loadingModels: 'Modeller alınıyor…',
    noModels: 'Model listesi alınamadı; model adını elle yazabilirsin.',
    groups: {
      keyless: 'Ücretsiz · kurulum yok',
      local: 'Ücretsiz · kendi makinen',
      byok: 'Kendi anahtarınla',
    },
    badges: {
      free: 'Ücretsiz',
      paid: 'Ücretli',
      device: 'Veri cihazında kalır',
      hosted: 'Veri sağlayıcıya gider',
      keyless: 'Anahtarsız',
      needsKey: 'Anahtar gerekir',
    },
    freeOnly: 'Yalnızca ücretsiz modeller',
    pullable: 'İndirilebilir ücretsiz modeller',
    copyCommand: 'Komutu kopyala',
    copied: 'Kopyalandı',
    localHint: 'Ollama kuruluysa otomatik seçilir — en gizli ve sınırsız seçenek.',
  },

  /* ---------------------------- AI bağlantı durumu ---------------------------- */
  ai: {
    checking: 'AI bağlantısı kontrol ediliyor…',
    online: 'Yerel AI hazır',
    offline: 'Yerel AI kapalı',
    modelMissing: 'Model kurulu değil',
    transportServer: 'sunucu üzerinden',
    transportDirect: 'tarayıcıdan doğrudan',
    model: 'Model',
    baseUrl: 'Adres',
    setup: 'Nasıl kurulur?',
    setupSteps: [
      'ollama.com adresinden Ollama’yı kur.',
      'Terminalde bir model indir: ollama pull qwen3:8b',
      'Tarayıcıdan doğrudan bağlanmak için Ollama’yı OLLAMA_ORIGINS=* ile başlat.',
    ],
    pull: (model: string) => `ollama pull ${model}`,
    recheck: 'Yeniden dene',
    preference: 'Bağlantı yolu',
    preferenceAuto: 'Otomatik',
    preferenceServer: 'Sunucu',
    preferenceDirect: 'Tarayıcı',
    save: 'Kaydet',
    saved: 'AI ayarları kaydedildi.',
  },

  /* ------------------------------ üretim ekranı ------------------------------ */
  generating: {
    title: 'Sunum hazırlanıyor',
    cancel: 'Vazgeç',
    steps: {
      analyze: 'İçerik analiz edildi',
      outline: 'Sunum akışı oluşturuldu',
      slides: 'Slaytlar yazılıyor',
      design: 'Tasarım uygulanıyor',
      check: 'Son kontroller yapılıyor',
    },
    slideN: (n: number) => `Slayt ${String(n).padStart(2, '0')}`,
    waiting: 'Model yanıt bekleniyor…',
    rateLimited: (sec: number) =>
      `Ücretsiz sağlayıcı hız sınırı verdi. ${sec} saniye beklenip aynı slayt yeniden denenecek — üretim iptal edilmiyor.`,
    done: 'Hazır',
  },

  /* --------------------------------- editör --------------------------------- */
  editor: {
    slides: 'Slaytlar',
    addSlide: 'Boş slayt ekle',
    aiAdd: 'AI ile slayt ekle',
    aiAddPlaceholder: 'Ne anlatsın? (boş bırakırsan konudan devam eder)',
    aiAddAuto: 'Tipi AI seçsin',
    aiAddCreate: 'Oluştur',
    aiAdding: 'Yazılıyor…',
    duplicateSlide: 'Kopyala',
    deleteSlide: 'Sil',
    moveUp: 'Yukarı taşı',
    moveDown: 'Aşağı taşı',
    dragHint: 'Sürükleyerek sırala',
    tabDesign: 'Tasarım',
    tabContent: 'İçerik',
    tabAi: 'AI',
    tabCoach: 'Koç',
    slideType: 'Slayt tipi',
    template: 'Yerleşim',
    theme: 'Tema',
    visual: 'Görsel yoğunluk',
    visualHint: 'İçeriği değiştirmez; yalnızca dekoratif katmanları ve sahnelemeyi ayarlar.',
    titleField: 'Başlık',
    subtitleField: 'Alt başlık',
    highlight: 'Vurgu cümlesi',
    highlightHint: 'Slayttan akılda kalması gereken tek cümle. Slaytın altında öne çıkar.',
    exampleField: 'Somut örnek',
    exampleHint: 'Bu slaydın söylediğinin gerçek hayattaki karşılığı. Slaytta ayrı bir bantta görünür.',
    iconField: 'Konu simgesi',
    iconHint: 'Başlığın yanındaki rozet. AI konuya göre seçer, değiştirebilirsin.',
    notesField: 'Konuşmacı notu',
    notesHint: 'PPTX çıktısına konuşmacı notu olarak yazılır.',
    bullets: 'Maddeler',
    addBullet: 'Madde ekle',
    leftColumn: 'Sol sütun',
    rightColumn: 'Sağ sütun',
    heading: 'Sütun başlığı',
    verdict: 'Sonuç cümlesi',
    stats: 'Ölçütler',
    statValue: 'Değer',
    statLabel: 'Etiket',
    statCaption: 'Açıklama',
    addStat: 'Ölçüt ekle',
    footnote: 'Dipnot',
    chartType: 'Grafik tipi',
    chartData: 'Veri',
    chartLabel: 'Etiket',
    chartValue: 'Değer',
    addPoint: 'Veri ekle',
    unit: 'Birim',
    caption: 'Alt yazı',
    steps: 'Adımlar',
    stepLabel: 'Dönem / etiket',
    stepTitle: 'Adım başlığı',
    stepDescription: 'Açıklama',
    addStep: 'Adım ekle',
    layers: 'Katmanlar',
    layerName: 'Katman adı',
    nodes: 'Bileşenler (virgülle ayır)',
    addLayer: 'Katman ekle',
    note: 'Not',
    glyph: 'Simge',
    image: 'Görsel',
    imageUpload: 'Görsel seç',
    imageRemove: 'Görseli kaldır',
    imageHint: 'Görsel küçültülerek cihazında saklanır.',
    quoteText: 'Alıntı',
    quoteAuthor: 'Kaynak',
    quoteRole: 'Ünvan',
    presenter: 'Sunan',
    context: 'Tarih / bağlam',
    cta: 'Kapanış cümlesi',
    remove: 'Kaldır',
    saved: 'Kaydedildi',
    saving: 'Kaydediliyor…',
    undo: 'Geri al',
    redo: 'Yinele',
    back: 'Sunumlarım',
    present: 'Sunumu Oynat',
    download: 'İndir',
    rename: 'Sunum adı',
    empty: 'Bu sunumda slayt yok.',
    emptyAction: 'İlk slaytı ekle',
  },

  /* ------------------------------- AI asistan ------------------------------- */
  assistant: {
    title: 'AI Asistan',
    subtitle: 'Seçili slaytı tek komutla yeniden yazar.',
    running: 'Çalışıyor…',
    undo: 'Geri al',
    undone: 'Değişiklik geri alındı.',
    applied: 'Slayt güncellendi.',
    needsAi: 'Bu bölüm bir AI bağlantısı gerektirir. AI sekmesinden bağlanabilirsin.',
    compareTitle: 'Yeni sürüm hazır',
    compareOld: 'Şu anki',
    compareNew: 'Yeni',
    use: 'Kullan',
    discard: 'Vazgeç',
  },

  /* -------------------------------- sunum koçu -------------------------------- */
  coach: {
    title: 'Sunum koçu',
    readiness: 'Hazırlık',
    timing: 'Süre planı',
    estimated: (a: number, b: number) => `Tahmini ${a} dk · hedef ${b} dk`,
    perSlide: 'Slayt başına',
    heaviest: 'En uzun slayt',
    allDone: 'Hazırlık tamam. Sunuma çıkabilirsin.',
    requirements: 'İsteklerin',
    statuses: {
      met: 'Karşılandı',
      missing: 'Görünmüyor',
      manual: 'Elle kontrol et',
    },
    writeAllNotes: 'Eksik notları AI ile yaz',
    writeAllHighlights: 'Eksik vurguları AI ile yaz',
    writeAllExamples: 'Eksik örnekleri AI ile yaz',
    visualize: 'Slaytları AI ile görselleştir',
    visualizing: (a: number, b: number) => `Görselleştiriliyor… ${a}/${b}`,
    visualized: (n: number) => `${n} slayt görsel biçime çevrildi.`,
    addSlide: (type: string) => `${type} ekle`,
    // Doldurma üç ayrı alanı da yazabiliyor; ileti hangisi olduğunu söylemeli.
    fillLabels: { notes: 'konuşmacı notu', highlight: 'vurgu cümlesi', example: 'somut örnek' },
    writingField: (a: number, b: number, what: string) => `${what} yazılıyor… ${a}/${b}`,
    fieldWritten: (n: number, what: string) => `${n} slayta ${what} eklendi.`,
    goTo: 'Slayda git',
    items: {
      'presenter-missing': 'Kapakta sunan kişi yazmıyor',
      'context-missing': 'Kapakta tarih / bağlam yok',
      'notes-missing': 'Konuşmacı notu olmayan slaytlar var',
      'highlight-missing': 'Çoğu slaytta vurgu cümlesi yok',
      'example-missing': 'Çoğu slaytta somut örnek yok',
      'no-conclusion': 'Sunum kapanış slaytıyla bitmiyor',
      'image-placeholder': 'Görsel slaytında hâlâ yer tutucu var',
      'flat-chart': 'Grafikteki değerler birbirinin aynı',
      'timing-over': 'Sunum hedeften uzun görünüyor',
      'timing-under': 'Sunum hedeften kısa görünüyor',
      'few-visuals': 'Sunum ağırlıklı olarak madde listesi',
    } as Record<CoachCode, string>,
    advice: {
      'presenter-missing': 'İçerik sekmesinden adını ve kurumunu ekle.',
      'context-missing': 'Tarih ya da bağlam eklemek sunumu kurumsal gösterir.',
      'notes-missing': 'Not yazmak süre tahminini de doğrular; AI ile tek tıkla yazdırabilirsin.',
      'highlight-missing': 'Her slaytta tek bir çıkarım, dinleyicinin aklında kalanı belirler.',
      'example-missing':
        'Doğru ama soyut maddeler akılda kalmıyor. Gerçek bir örnek, iddiayı dinleyicinin kendi dünyasına bağlar.',
      'no-conclusion': 'Son slaytı "Kapanış" tipine çevir ya da yeni bir kapanış ekle.',
      'image-placeholder': 'Kendi görselini yükle ya da slaytı görsel olmayan bir tipe çevir.',
      'flat-chart': 'Aynı değerler grafiği anlamsız kılar; veriyi güncelle ya da tipi değiştir.',
      'timing-over': 'Metni kısalt ya da slayt çıkar. En uzun slayttan başla.',
      'timing-under': 'Slayt ekleyebilir ya da örneklerle derinleştirebilirsin.',
      'few-visuals':
        'Uygun slaytlar grafiğe, büyük sayıya, sürece ya da zaman çizelgesine çevrilebilir. AI her birini tek tek dönüştürür.',
    } as Record<CoachCode, string>,
  },

  /* ------------------------------ kalite kontrol ------------------------------ */
  quality: {
    title: 'Sunum kalitesi',
    score: 'Kalite puanı',
    recheck: 'Yeniden denetle',
    checking: 'Denetleniyor…',
    clean: 'Sorun bulunmadı. Sunum gösterime hazır.',
    fix: 'Düzelt',
    fixAll: 'Düzeltilebilenleri uygula',
    fixed: (n: number) => `${n} düzeltme uygulandı.`,
    noFix: 'Otomatik düzeltilemez',
    goTo: 'Slayda git',
    engineLocal: 'Yerel denetim',
    engineJev: 'Jev derin analiz',
    engineGateway: 'Gateway derin analiz',
    byRule: 'ölçüm',
    byAi: 'AI',
    deep: 'Jev ile derin analiz',
    deepHint:
      'Açarsan slayt METNİ analiz için TypeSafe AI (Jev) servisine gönderilir. Kapalıyken her şey cihazında kalır.',
    deepUnavailable:
      'Bu kurulumda karar motoru anahtarı yok. TYPESAFE_API_KEY (Jev) ya da Vercel entegrasyonunun eklediği AI_GATEWAY_API_KEY tanımlanabilir.',
    deckWide: 'Sunum geneli',
    issues: {
      'title-long': 'Başlık çok uzun',
      'too-many-bullets': 'Slaytta çok fazla madde var',
      'bullet-long': 'Bir madde fazla uzun',
      overflow: 'İçerik slayda sığmıyor',
      empty: 'Slayt boş',
      'template-repeat': 'Aynı yerleşim üst üste tekrar ediyor',
      contrast: 'Renk kontrastı düşük',
      monotone: 'Sunum tek tip slayttan oluşuyor',
      dense: 'Slayt arka sıradan okunamayacak kadar dolu',
      unclear: 'Başlık ve ana mesaj yeterince net değil',
      'visual-mismatch': 'Bu içerik görsel bir biçime daha uygun',
    } as Record<IssueCode, string>,
    fixes: {
      split: 'İkiye böl',
      'trim-title': 'Başlığı kısalt',
      'to-chart': 'Grafiğe çevir',
      'to-stats': 'Büyük sayıya çevir',
      'to-process': 'Sürece çevir',
      retemplate: 'Yerleşimi değiştir',
      none: '',
    },
  },

  /* --------------------------------- çıktı --------------------------------- */
  exportPanel: {
    title: 'İndir',
    fileName: 'Dosya adı',
    pptx: 'PowerPoint (.pptx)',
    pdf: 'PDF olarak yazdır',
    json: 'JSON yedeği',
    pptxBusy: 'PPTX hazırlanıyor…',
    pdfBusy: 'Yazdırma açılıyor…',
    pptxDone: 'PPTX indirildi.',
    hint: 'PPTX düzenlenebilir olarak iner; grafikler PowerPoint grafiği olarak gelir.',
  },

  /* ------------------------------- sunum modu ------------------------------- */
  previewer: {
    exit: 'Çık',
    next: 'Sonraki',
    prev: 'Önceki',
    counter: (i: number, n: number) => `${i} / ${n}`,
    notes: 'Notlar',
    overview: 'Tüm slaytlar',
    fullscreen: 'Tam ekran',
    exitFullscreen: 'Tam ekrandan çık',
    transition: 'Geçiş',
    transitions: { fade: 'Yumuşak', slide: 'Kaydır', none: 'Yok' },
    hint: '← → gez · F tam ekran · O genel görünüm · N notlar · Esc çık',
  },

  audiences: {
    professional: 'Profesyonel',
    student: 'Öğrenciler',
    employee: 'Çalışanlar',
    management: 'Yönetim',
    technical: 'Teknik Ekip',
    customer: 'Müşteriler',
    academic: 'Akademik',
    general: 'Genel Kitle',
  } as Record<Audience, string>,

  audienceHints: {
    professional: 'Hiçbir ayrıntı elenmez; terim kullanılır ve tanımlanır',
    student: 'Terimler tanımlanır, örnek verilir',
    employee: 'Günlük işe etkisi öne çıkar',
    management: 'Maliyet, risk ve karar noktaları',
    technical: 'Mimari ve somut teknolojiler',
    customer: 'Fayda odaklı, jargonsuz',
    academic: 'Yöntem, bulgu ve kaynak mantığı',
    general: 'Ön bilgi varsayılmaz',
  } as Record<Audience, string>,

  visuals: {
    clean: 'Sade',
    modern: 'Modern',
    bold: 'Çarpıcı',
  } as Record<Visual, string>,

  depths: {
    fast: {
      label: 'Hızlı',
      hint: 'Tek AI çağrısı. Yaklaşık yarım dakikada biter; maddeler kısadır.',
    },
    deep: {
      label: 'Derin araştırma',
      hint: 'Önce plan, sonra slayt başına ayrı çağrı. Birkaç dakika sürer; maddeler tam cümle olur, her slayta somut örnek girer ve yüklenen dokümanın ilgili bölümü slayt slayt işlenir.',
    },
  } as Record<Depth, { label: string; hint: string }>,

  tones: {
    professional: 'Profesyonel',
    academic: 'Akademik',
    friendly: 'Samimi',
    persuasive: 'İkna edici',
  } as Record<Tone, string>,

  slideTypes: {
    title: 'Kapak',
    content: 'İçerik',
    'two-column': 'İki sütun',
    comparison: 'Karşılaştırma',
    statistics: 'İstatistik',
    chart: 'Grafik',
    timeline: 'Zaman çizelgesi',
    process: 'Süreç',
    architecture: 'Mimari',
    image: 'Görsel',
    quote: 'Alıntı',
    conclusion: 'Kapanış',
  } as Record<SlideType, string>,

  chartKinds: { bar: 'Sütun', line: 'Çizgi', pie: 'Pasta', donut: 'Halka' },

  refine: {
    shorten: 'Metni kısalt',
    professional: 'Daha profesyonel yap',
    simplify: 'Öğrenci seviyesine indir',
    toBullets: '3 maddeye dönüştür',
    toChart: 'Grafiğe dönüştür',
    toProcess: 'Süreç diyagramına çevir',
    toTimeline: 'Zaman çizelgesine çevir',
    toStats: 'Büyük sayılara çevir',
    toComparison: 'Karşılaştırmaya çevir',
    toArchitecture: 'Mimari şemaya çevir',
    expand: 'İçeriği genişlet',
    notes: 'Konuşmacı notu yaz',
    highlight: 'Vurgu cümlesi yaz',
    example: 'Somut örnek ekle',
  } as Record<RefineAction, string>,

  /* ------------------------- girdi kaynağı ve AI'nın rolü ------------------------- */
  sourceModes: {
    'topic-ai': {
      label: 'Sadece konu · AI yazsın',
      hint: 'Tek cümlelik konu veriyorsun, içeriği baştan sona AI araştırıp yazıyor.',
    },
    'text-only': {
      label: 'Sadece metin · AI kullanma',
      hint: 'Yapıştırdığın metin olduğu gibi slaytlara bölünür. Hiçbir AI çağrısı yapılmaz, hiçbir cümle değiştirilmez.',
    },
    'text-ai': {
      label: 'Metin + AI',
      hint: 'Yapıştırdığın metni AI yeniden düzenler, başlıklandırır ve görsel slaytlara dönüştürür.',
    },
    'doc-only': {
      label: 'Sadece doküman · AI kullanma',
      hint: 'Yüklediğin dosyanın metni olduğu gibi slaytlara bölünür. Hiçbir AI çağrısı yapılmaz.',
    },
    'doc-ai': {
      label: 'Doküman + AI',
      hint: 'Yüklediğin dosya bölüm bölüm çözümlenir; AI her slaytı ilgili bölümden yazar.',
    },
  } as Record<SourceMode, { label: string; hint: string }>,

  sourceModeTitle: 'Nasıl ilerleyelim?',
  sourceModeSub: 'Girdiyi ve AI’nın rolünü sen seçersin; sistem tahmin etmez.',
  sourceModeNeedsText: 'Bu mod için metin yapıştırman gerekiyor.',
  sourceModeNeedsDoc: 'Bu mod için bir dosya yüklemen gerekiyor.',
  sourceModeNoAi: 'Bu modda AI çağrısı yapılmaz.',

  /* ----------------------------- içerik standardı ----------------------------- */
  frameworks: {
    classic: { label: 'Klasik', hint: 'Tanım → veriler → sorunlar → çözüm → sonuç. Her konuya oturan genel iskelet.' },
    'problem-solution': { label: 'Problem · Çözüm', hint: 'Sorunu büyüt, bedelini göster, çözümü ve uygulama adımlarını ver.' },
    story: { label: 'Hikâye', hint: 'Durum → çatışma → dönüm noktası → çözülme. Akılda en çok kalan kurgu.' },
    pyramid: { label: 'Piramit (Minto)', hint: 'Sonucu başta söyle, sonra gerekçeleri ve kanıtları sırala. Yöneticiye en uygun.' },
    swot: { label: 'SWOT', hint: 'Güçlü yönler, zayıf yönler, fırsatlar, tehditler ve çıkarım.' },
    'case-study': { label: 'Vaka analizi', hint: 'Bağlam → yapılanlar → ölçülen sonuç → çıkarılan dersler.' },
    academic: { label: 'Akademik', hint: 'Giriş → literatür → yöntem → bulgular → tartışma → kaynakça.' },
    pitch: { label: 'Yatırımcı sunumu', hint: 'Problem → çözüm → pazar → iş modeli → ekip → talep.' },
    training: { label: 'Eğitim', hint: 'Kazanımlar → kavramlar → örnek → uygulama → özet → değerlendirme.' },
    retrospective: { label: 'Değerlendirme', hint: 'Hedef → yapılanlar → sayılar → iyi/kötü giden → sonraki dönem.' },
  } as Record<Framework, { label: string; hint: string }>,

  frameworkTitle: 'İçerik standardı',
  frameworkSub: 'Sunumun anlatım iskeleti. Bölümleri aşağıda görebilirsin.',
  frameworkSections: 'Bölümler',

  /* --------------------------------- görseller --------------------------------- */
  media: {
    title: 'Görsel',
    aiGenerate: 'AI ile görsel üret',
    generating: 'Görsel üretiliyor…',
    prompt: 'Görselde ne olsun?',
    promptHint: 'Boş bırakırsan slaytın başlığı ve içeriği kullanılır.',
    style: 'Görsel üslubu',
    styles: {
      photo: 'Fotoğraf',
      illustration: 'İllüstrasyon',
      flat: 'Düz vektör',
      isometric: 'İzometrik',
      minimal: 'Minimal',
      blueprint: 'Teknik çizim',
    },
    upload: 'Dosyadan yükle',
    uploadHint: 'PNG, JPG, WEBP ya da GIF · en fazla 800 KB',
    remove: 'Görseli kaldır',
    replace: 'Değiştir',
    failed: 'Görsel üretilemedi. Tekrar deneyebilir ya da kendi dosyanı yükleyebilirsin.',
    quota:
      'Ücretsiz görsel servisinin kotası şu an dolu. Birkaç dakika sonra tekrar dene ya da kendi dosyanı yükle.',
    tooLarge: 'Görsel çok büyük; küçültülemedi.',
    provider: 'Anahtarsız ücretsiz görsel servisi kullanılır; istem sağlayıcıya gönderilir.',
    animatedNote: 'Hareketli GIF üretimi ücretsiz sağlayıcılarda yok — kendi GIF dosyanı yükleyebilirsin.',
    placement: 'Yerleşim',
    placements: {
      background: 'Zemin',
      band: 'Alt şerit',
      inset: 'Köşe kutusu',
    },
    placementHints: {
      background: 'Slaydın tamamını kaplar, metin okunabilir kalsın diye üstüne perde çekilir.',
      band: 'Gövdenin altında tam genişlik bir şerit.',
      inset: 'Sağa yaslı küçük çerçeve.',
    },
    fit: 'Çerçeveye oturma',
    fits: { cover: 'Doldur (kırpar)', contain: 'Sığdır (tamamı görünür)' },
    frame: 'Görseli çerçevede konumlandır',
    frameHint: 'Görseli sürükleyerek odağı değiştir, tekerlekle ya da kaydırıcıyla yakınlaştır.',
    zoom: 'Yakınlaştırma',
    reset: 'Sıfırla',
    altLabel: 'Görsel açıklaması',
    altHint: 'Ekran okuyucular ve PPTX çıktısı için. Boş bırakılabilir.',
  },

  /* ------------------------------ metin biçimi ------------------------------ */
  format: {
    title: 'Metin biçimi',
    hint: 'Bu slaydın tüm metnine uygulanır. Renk ve yazı tipi temaya bağlıdır; kontrast korunur.',
    font: 'Yazı tipi',
    fonts: {
      theme: 'Tema yazı tipi',
      sans: 'Sans (Inter)',
      serif: 'Serif (Georgia)',
      display: 'Başlık tipi',
      mono: 'Eş aralıklı',
    },
    size: 'Punto',
    smaller: 'Küçült',
    bigger: 'Büyüt',
    bold: 'Kalın',
    italic: 'İtalik',
    underline: 'Altı çizili',
    align: 'Hizalama',
    aligns: { left: 'Sola', center: 'Ortaya', right: 'Sağa' },
    tone: 'Renk',
    tones: { default: 'Varsayılan', accent: 'Vurgu', muted: 'Soluk' },
    lineHeight: 'Satır aralığı',
    reset: 'Biçimi sıfırla',
    resetHint: 'Slayt temanın kendi biçimine döner.',
  },

  glyphs: {
    idea: 'Fikir',
    chart: 'Veri',
    growth: 'Büyüme',
    users: 'İnsanlar',
    gear: 'Süreç',
    shield: 'Güvenlik',
    cloud: 'Bulut',
    code: 'Kod',
    target: 'Hedef',
    clock: 'Zaman',
    book: 'Kaynak',
    money: 'Maliyet',
    warning: 'Risk',
    check: 'Onay',
    search: 'Araştırma',
    globe: 'Küresel',
    rocket: 'Başlangıç',
    network: 'Ağ',
    database: 'Veritabanı',
    mobile: 'Mobil',
    energy: 'Enerji',
    health: 'Sağlık',
    leaf: 'Sürdürülebilirlik',
    lock: 'Gizlilik',
    message: 'İletişim',
    star: 'Kalite',
    calendar: 'Takvim',
    layers: 'Katman',
    flask: 'Deney',
    scale: 'Hukuk / denge',
  },
}

const EN: typeof TR = {
  appTitle: 'AI Presentation Studio',
  appSub:
    'Type a topic or upload a PDF/DOCX; the AI builds the content and flow, the Slide Engine builds the design. Download as PPTX or PDF.',
  freeBadge: 'Free · Local AI (Ollama) · No sign-up · Your data stays on your device',

  hero: {
    eyebrow: 'AI Presentation Studio',
    title: 'Stop losing hours to slide decks.',
    lead: 'Describe your topic. Get a professional deck in seconds.',
    question: 'What would you like a presentation about?',
    placeholder: 'The impact of artificial intelligence on education',
    cta: 'Create Deck',
    or: 'or',
    pdf: 'Upload PDF',
    docx: 'Upload Word',
    paste: 'Paste Text',
    chipsLabel: 'Quick start',
    chips: [
      { label: 'University project', topic: 'The goal, method and results of my final project', audience: 'student' },
      { label: 'Management update', topic: 'This quarter’s results and next quarter’s plan', audience: 'management' },
      { label: 'Technical project', topic: 'The new system architecture and migration plan', audience: 'technical' },
      { label: 'Academic talk', topic: 'The method, findings and contribution of the research', audience: 'academic' },
      { label: 'Sales deck', topic: 'The problem the product solves and what customers gain', audience: 'customer' },
    ],
    how: 'How it works',
    steps: [
      { title: 'Give a topic', body: 'One sentence is enough. Or upload your PDF or Word file.' },
      { title: 'Make three picks', body: 'Audience, length and theme. Everything else has a sensible default.' },
      { title: 'Get the deck', body: 'Slides appear, you edit, then download PPTX or PDF.' },
    ],
  },

  library: {
    title: 'My decks',
    empty: 'No decks yet.',
    emptyHint: 'Build your first deck in a few seconds.',
    create: 'New Deck',
    open: 'Open',
    duplicate: 'Duplicate',
    remove: 'Delete',
    removeConfirm: 'This deck will be deleted from your device. Are you sure?',
    removed: 'Deck deleted.',
    slides: (n: number) => `${n} slides`,
    minutes: (n: number) => `${n} min`,
    updated: 'Last edited',
    aiBadge: 'AI draft',
    outlineBadge: 'Local draft',
    copySuffix: '(copy)',
  },

  wizard: {
    steps: [
      { title: 'Content', sub: 'What will you cover?' },
      { title: 'Settings', sub: 'Length, framework and language' },
      { title: 'Design', sub: 'Pick a theme' },
    ],
    stepOf: (i: number, n: number) => `Step ${i} / ${n}`,
    next: 'Continue',
    back: 'Back',
    create: 'Create the Deck',
    cancel: 'Cancel',
  },

  form: {
    topic: 'What do you want to present?',
    topicPlaceholder: 'e.g. Using artificial intelligence in education',
    topicHint: 'One clear sentence gives the best result.',
    description: 'Description / source text',
    descriptionPlaceholder: 'Paste the notes, figures or text you want the deck to cover (optional).',
    pasteToggle: 'Paste Text',
    upload: 'Upload PDF / Word / text',
    dropHere: 'Drop the file here',
    dropHint: 'PDF, DOCX, TXT or MD · 10 MB max · the file never leaves your device',
    analyzing: 'Analysing the file…',
    uploadDone: (name: string, chars: number) => `${name} · ${chars.toLocaleString('en-US')} characters extracted`,
    uploadRemove: 'Remove',
    audience: 'Audience',
    duration: 'Talk length',
    slideCount: 'Slide count',
    theme: 'Design theme',
    language: 'Language',
    tone: 'Deck style',
    requirements: 'What the deck should include',
    requirementsHint:
      'Write it in your own words; the AI interprets it and applies it to the structure. Optional.',
    requirementsPlaceholder:
      'e.g. Give a real example in every section. Show the figures as charts. Add a sources slide at the end.',
    requirementChips: [
      'Back it with charts',
      'An example in every section',
      'Add a process diagram',
      'Prove it with numbers',
      'Add a timeline',
      'Add a sources slide',
      'Keep it short and sharp',
      'Use storytelling',
    ],
    advanced: 'Advanced settings',
    depth: 'Generation depth',
    minutesUnit: 'minutes',
    slidesUnit: 'slides',
    aiConnection: 'AI connection',
  },

  errors: {
    topicRequired: 'Write a topic.',
    fileTooLarge: 'File too large (10 MB max).',
    fileType: 'Only PDF and DOCX files are supported.',
    fileEmpty: 'No text could be extracted. It may be a scanned (image) PDF.',
    fileFailed: 'The file could not be read.',
    notFound: 'Deck not found.',
    notFoundHint: 'The link may be stale, or the deck was deleted from this device.',
    saveQuota: 'Device storage is full. Delete one of the older decks.',
    generic: 'The deck could not be created.',
    retry: 'Try Again',
    aiOffline: 'The local AI service is unreachable.',
    openConnection: 'Set up connection',
    aiOfflineDetail:
      'The AI service could not be reached. A local draft was built from your text; connect and regenerate any time.',
    quotaDetail:
      'The free model’s quota is used up. A local draft was built from your text; try again in a few minutes, switch to another free model, or add your own key.',
    refineFailed: 'The AI command could not be completed.',
    exportFailed: 'The file could not be created.',
  },

  install: {
    title: 'Local model setup',
    subtitle: 'No terminal knowledge needed — just follow the steps.',
    open: 'Setup wizard',
    close: 'Close',
    step1: '1. Install Ollama',
    step2: '2. Allow the browser',
    step3: '3. Download a model',
    checking: 'Looking for Ollama…',
    found: 'Ollama is running',
    notFound: 'Ollama not found',
    downloadApp: 'Download Ollama',
    orCommand: 'or paste into a terminal:',
    serveHint: 'After installing, start Ollama with this command — the browser needs it to connect.',
    waiting: 'Waiting for the installation to finish…',
    waitingFor: (s: number) => `Waiting · ${s}s`,
    startService: 'Start Ollama',
    startingService: 'Starting Ollama…',
    serviceStarted: 'Ollama started.',
    serviceNotInstalled: 'Ollama was not found on this machine. Finish step 1 first.',
    serviceFailed: 'Could not start Ollama. If it is installed, try opening the app once manually.',
    startWaiting: 'I installed it, check',
    stopWaiting: 'Stop waiting',
    installed: 'Installed',
    install: 'Install',
    installing: 'Downloading…',
    cancel: 'Cancel',
    pullStatus: {
      manifest: 'Fetching model info',
      downloading: 'Downloading',
      verifying: 'Verifying',
      writing: 'Writing',
      success: 'Done',
    },
    done: (name: string) => `${name} installed and selected.`,
    errors: {
      unreachable: 'Could not reach Ollama. Try the “Start Ollama” button below.',
      'not-found': 'That model was not found in the Ollama library.',
      failed: 'The download could not be completed.',
    },
    why: 'Why a local model?',
    whyBody:
      'Free, unlimited, and your slide text never leaves the device. Once installed it works without internet.',
  },

  connection: {
    title: 'AI connection',
    connected: 'Connected',
    connecting: 'Connecting…',
    offline: 'Could not connect',
    autoConnected: 'Connected automatically',
    provider: 'Provider',
    model: 'Model',
    apiKey: 'API key',
    apiKeyHint: 'The key is stored only in this browser; it is never sent to this site’s server.',
    apiKeyPlaceholder: 'sk-…',
    getKey: 'Get a key',
    baseUrl: 'Base URL',
    baseUrlPlaceholder: 'https://api.example.com/v1',
    modelPlaceholder: 'model-name',
    save: 'Save connection',
    saved: 'Connection saved.',
    reset: 'Reset to default',
    retry: 'Try again',
    needsKey: 'Enter an API key for this provider.',
    loadingModels: 'Fetching models…',
    noModels: 'Could not fetch the model list; you can type the model name.',
    groups: {
      keyless: 'Free · no setup',
      local: 'Free · your machine',
      byok: 'Bring your own key',
    },
    badges: {
      free: 'Free',
      paid: 'Paid',
      device: 'Data stays on device',
      hosted: 'Data goes to provider',
      keyless: 'No key',
      needsKey: 'Key required',
    },
    freeOnly: 'Free models only',
    pullable: 'Free models you can download',
    copyCommand: 'Copy command',
    copied: 'Copied',
    localHint: 'Picked automatically when Ollama is installed — the most private, unlimited option.',
  },

  ai: {
    checking: 'Checking the AI connection…',
    online: 'Local AI ready',
    offline: 'Local AI offline',
    modelMissing: 'Model not installed',
    transportServer: 'via server',
    transportDirect: 'direct from browser',
    model: 'Model',
    baseUrl: 'Address',
    setup: 'How to set up?',
    setupSteps: [
      'Install Ollama from ollama.com.',
      'Pull a model: ollama pull qwen3:8b',
      'To connect straight from the browser, start Ollama with OLLAMA_ORIGINS=*.',
    ],
    pull: (model: string) => `ollama pull ${model}`,
    recheck: 'Try again',
    preference: 'Connection path',
    preferenceAuto: 'Automatic',
    preferenceServer: 'Server',
    preferenceDirect: 'Browser',
    save: 'Save',
    saved: 'AI settings saved.',
  },

  generating: {
    title: 'Building your deck',
    cancel: 'Cancel',
    steps: {
      analyze: 'Content analysed',
      outline: 'Deck outline built',
      slides: 'Writing slides',
      design: 'Applying the design',
      check: 'Running final checks',
    },
    slideN: (n: number) => `Slide ${String(n).padStart(2, '0')}`,
    waiting: 'Waiting for the model…',
    rateLimited: (sec: number) =>
      `The free provider rate-limited us. Retrying the same slide in ${sec}s — generation is not cancelled.`,
    done: 'Ready',
  },

  editor: {
    slides: 'Slides',
    addSlide: 'Add blank slide',
    aiAdd: 'Add slide with AI',
    aiAddPlaceholder: 'What should it cover? (leave empty to continue the topic)',
    aiAddAuto: 'Let the AI pick the type',
    aiAddCreate: 'Create',
    aiAdding: 'Writing…',
    duplicateSlide: 'Duplicate',
    deleteSlide: 'Delete',
    moveUp: 'Move up',
    moveDown: 'Move down',
    dragHint: 'Drag to reorder',
    tabDesign: 'Design',
    tabContent: 'Content',
    tabAi: 'AI',
    tabCoach: 'Coach',
    slideType: 'Slide type',
    template: 'Layout',
    theme: 'Theme',
    visual: 'Visual intensity',
    visualHint: 'Does not change the content; only the decorative layers and staging.',
    titleField: 'Title',
    subtitleField: 'Subtitle',
    highlight: 'Takeaway',
    highlightHint: 'The one sentence that should stick. Shown at the bottom of the slide.',
    exampleField: 'Concrete example',
    exampleHint: 'What this slide looks like in real life. Shown in its own band on the slide.',
    iconField: 'Subject icon',
    iconHint: 'The badge next to the title. AI picks it from the subject; you can change it.',
    notesField: 'Speaker note',
    notesHint: 'Written into the PPTX as a speaker note.',
    bullets: 'Bullets',
    addBullet: 'Add bullet',
    leftColumn: 'Left column',
    rightColumn: 'Right column',
    heading: 'Column heading',
    verdict: 'Verdict',
    stats: 'Metrics',
    statValue: 'Value',
    statLabel: 'Label',
    statCaption: 'Caption',
    addStat: 'Add metric',
    footnote: 'Footnote',
    chartType: 'Chart type',
    chartData: 'Data',
    chartLabel: 'Label',
    chartValue: 'Value',
    addPoint: 'Add data point',
    unit: 'Unit',
    caption: 'Caption',
    steps: 'Steps',
    stepLabel: 'Period / label',
    stepTitle: 'Step title',
    stepDescription: 'Description',
    addStep: 'Add step',
    layers: 'Layers',
    layerName: 'Layer name',
    nodes: 'Components (comma separated)',
    addLayer: 'Add layer',
    note: 'Note',
    glyph: 'Icon',
    image: 'Image',
    imageUpload: 'Choose image',
    imageRemove: 'Remove image',
    imageHint: 'The image is downscaled and stored on your device.',
    quoteText: 'Quote',
    quoteAuthor: 'Source',
    quoteRole: 'Role',
    presenter: 'Presenter',
    context: 'Date / context',
    cta: 'Closing line',
    remove: 'Remove',
    saved: 'Saved',
    saving: 'Saving…',
    undo: 'Undo',
    redo: 'Redo',
    back: 'My decks',
    present: 'Present',
    download: 'Download',
    rename: 'Deck name',
    empty: 'This deck has no slides.',
    emptyAction: 'Add the first slide',
  },

  assistant: {
    title: 'AI Assistant',
    subtitle: 'Rewrites the selected slide with one command.',
    running: 'Working…',
    undo: 'Undo',
    undone: 'Change undone.',
    applied: 'Slide updated.',
    needsAi: 'This needs an AI connection. Connect from the AI tab.',
    compareTitle: 'New version ready',
    compareOld: 'Current',
    compareNew: 'New',
    use: 'Use it',
    discard: 'Discard',
  },

  coach: {
    title: 'Presentation coach',
    readiness: 'Readiness',
    timing: 'Timing plan',
    estimated: (a: number, b: number) => `Est. ${a} min · target ${b} min`,
    perSlide: 'Per slide',
    heaviest: 'Longest slide',
    allDone: 'You are ready to present.',
    requirements: 'Your requests',
    statuses: {
      met: 'Met',
      missing: 'Not visible',
      manual: 'Check manually',
    },
    writeAllNotes: 'Write missing notes with AI',
    writeAllHighlights: 'Write missing takeaways with AI',
    writeAllExamples: 'Write missing examples with AI',
    visualize: 'Visualise slides with AI',
    visualizing: (a: number, b: number) => `Visualising… ${a}/${b}`,
    visualized: (n: number) => `${n} slides turned into visual form.`,
    addSlide: (type: string) => `Add ${type}`,
    fillLabels: { notes: 'speaker notes', highlight: 'a takeaway', example: 'a concrete example' },
    writingField: (a: number, b: number, what: string) => `Writing ${what}… ${a}/${b}`,
    fieldWritten: (n: number, what: string) => `Added ${what} to ${n} slides.`,
    goTo: 'Go to slide',
    items: {
      'presenter-missing': 'The cover has no presenter',
      'context-missing': 'The cover has no date / context',
      'notes-missing': 'Some slides have no speaker notes',
      'highlight-missing': 'Most slides have no takeaway',
      'example-missing': 'Most slides have no concrete example',
      'no-conclusion': 'The deck does not end with a closing slide',
      'image-placeholder': 'An image slide still shows a placeholder',
      'flat-chart': 'All chart values are identical',
      'timing-over': 'The deck looks longer than the target',
      'timing-under': 'The deck looks shorter than the target',
      'few-visuals': 'The deck is mostly bullet lists',
    },
    advice: {
      'presenter-missing': 'Add your name and organisation from the Content tab.',
      'context-missing': 'A date or context makes the deck look more considered.',
      'notes-missing': 'Notes also validate the timing estimate; the AI can write them in one click.',
      'highlight-missing': 'One takeaway per slide decides what the audience remembers.',
      'example-missing':
        'Correct but abstract bullets do not stick. A real example ties the claim to the audience\'s own world.',
      'no-conclusion': 'Convert the last slide to "Closing" or add a new closing slide.',
      'image-placeholder': 'Upload your own image or switch the slide to a non-image type.',
      'flat-chart': 'Identical values make the chart meaningless; update the data or change the type.',
      'timing-over': 'Shorten the text or drop a slide. Start with the longest one.',
      'timing-under': 'You can add slides or deepen with examples.',
      'few-visuals':
        'Suitable slides can become charts, big numbers, processes or timelines. The AI converts them one by one.',
    },
  },

  quality: {
    title: 'Deck quality',
    score: 'Quality score',
    recheck: 'Re-check',
    checking: 'Checking…',
    clean: 'No issues found. The deck is ready to present.',
    fix: 'Fix',
    fixAll: 'Apply all safe fixes',
    fixed: (n: number) => `${n} fixes applied.`,
    noFix: 'No automatic fix',
    goTo: 'Go to slide',
    engineLocal: 'Local check',
    engineJev: 'Jev deep analysis',
    engineGateway: 'Gateway deep analysis',
    byRule: 'measured',
    byAi: 'AI',
    deep: 'Deep analysis with Jev',
    deepHint:
      'If enabled, slide TEXT is sent to TypeSafe AI (Jev) for analysis. While off, everything stays on your device.',
    deepUnavailable:
      'No decision-engine key in this deployment. Set TYPESAFE_API_KEY (Jev) or the AI_GATEWAY_API_KEY added by the Vercel integration.',
    deckWide: 'Deck-wide',
    issues: {
      'title-long': 'Title is too long',
      'too-many-bullets': 'Too many bullets on this slide',
      'bullet-long': 'One bullet is too long',
      overflow: 'Content does not fit the slide',
      empty: 'Slide is empty',
      'template-repeat': 'The same layout repeats back to back',
      contrast: 'Colour contrast is low',
      monotone: 'The deck is all one slide type',
      dense: 'Too dense to read from the back row',
      unclear: 'Title and main message are not clear enough',
      'visual-mismatch': 'This content suits a visual form better',
    },
    fixes: {
      split: 'Split in two',
      'trim-title': 'Shorten the title',
      'to-chart': 'Turn into a chart',
      'to-stats': 'Turn into big numbers',
      'to-process': 'Turn into a process',
      retemplate: 'Change the layout',
      none: '',
    },
  },

  exportPanel: {
    title: 'Download',
    fileName: 'File name',
    pptx: 'PowerPoint (.pptx)',
    pdf: 'Print to PDF',
    json: 'JSON backup',
    pptxBusy: 'Preparing PPTX…',
    pdfBusy: 'Opening print…',
    pptxDone: 'PPTX downloaded.',
    hint: 'The PPTX is fully editable; charts arrive as native PowerPoint charts.',
  },

  previewer: {
    exit: 'Exit',
    next: 'Next',
    prev: 'Previous',
    counter: (i: number, n: number) => `${i} / ${n}`,
    notes: 'Notes',
    overview: 'All slides',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit fullscreen',
    transition: 'Transition',
    transitions: { fade: 'Fade', slide: 'Slide', none: 'None' },
    hint: '← → navigate · F fullscreen · O overview · N notes · Esc exit',
  },

  audiences: {
    professional: 'Professional',
    student: 'Students',
    employee: 'Employees',
    management: 'Management',
    technical: 'Engineering',
    customer: 'Customers',
    academic: 'Academic',
    general: 'General',
  },

  audienceHints: {
    professional: 'No detail dropped; terms used and defined',
    student: 'Terms defined, examples given',
    employee: 'Day-to-day impact first',
    management: 'Cost, risk and decision points',
    technical: 'Architecture and concrete tech',
    customer: 'Benefit-first, no jargon',
    academic: 'Method, findings and sourcing',
    general: 'No prior knowledge assumed',
  },

  visuals: {
    clean: 'Clean',
    modern: 'Modern',
    bold: 'Bold',
  },

  depths: {
    fast: {
      label: 'Fast',
      hint: 'One AI call. Finishes in about half a minute; bullets stay short.',
    },
    deep: {
      label: 'Deep research',
      hint: 'A plan first, then one call per slide. Takes a few minutes; bullets become full sentences, every slide gets a concrete example, and an uploaded document is worked through section by section.',
    },
  } as Record<Depth, { label: string; hint: string }>,

  tones: {
    professional: 'Professional',
    academic: 'Academic',
    friendly: 'Friendly',
    persuasive: 'Persuasive',
  },

  slideTypes: {
    title: 'Cover',
    content: 'Content',
    'two-column': 'Two column',
    comparison: 'Comparison',
    statistics: 'Statistics',
    chart: 'Chart',
    timeline: 'Timeline',
    process: 'Process',
    architecture: 'Architecture',
    image: 'Image',
    quote: 'Quote',
    conclusion: 'Closing',
  },

  chartKinds: { bar: 'Column', line: 'Line', pie: 'Pie', donut: 'Donut' },

  refine: {
    shorten: 'Shorten the text',
    professional: 'Make it more professional',
    simplify: 'Bring to student level',
    toBullets: 'Turn into 3 bullets',
    toChart: 'Turn into a chart',
    toProcess: 'Turn into a process diagram',
    toTimeline: 'Turn into a timeline',
    toStats: 'Turn into big numbers',
    toComparison: 'Turn into a comparison',
    toArchitecture: 'Turn into an architecture diagram',
    expand: 'Expand the content',
    notes: 'Write a speaker note',
    highlight: 'Write the takeaway',
    example: 'Add a concrete example',
  },

  sourceModes: {
    'topic-ai': {
      label: 'Topic only · let AI write',
      hint: 'You give a one-line topic; AI researches and writes the whole deck.',
    },
    'text-only': {
      label: 'Text only · no AI',
      hint: 'Your pasted text is split into slides as-is. No AI call is made, no sentence is rewritten.',
    },
    'text-ai': {
      label: 'Text + AI',
      hint: 'AI restructures your text, gives it headings and turns parts of it into visual slides.',
    },
    'doc-only': {
      label: 'Document only · no AI',
      hint: 'The text of your file is split into slides as-is. No AI call is made.',
    },
    'doc-ai': {
      label: 'Document + AI',
      hint: 'Your file is analysed section by section; AI writes each slide from the matching section.',
    },
  } as Record<SourceMode, { label: string; hint: string }>,

  sourceModeTitle: 'How should we proceed?',
  sourceModeSub: 'You choose the input and the role of AI; the system does not guess.',
  sourceModeNeedsText: 'This mode needs pasted text.',
  sourceModeNeedsDoc: 'This mode needs an uploaded file.',
  sourceModeNoAi: 'No AI call is made in this mode.',

  frameworks: {
    classic: { label: 'Classic', hint: 'Definition → data → problems → solution → conclusion. Fits any subject.' },
    'problem-solution': { label: 'Problem · Solution', hint: 'Frame the problem, show its cost, give the solution and rollout steps.' },
    story: { label: 'Story', hint: 'Situation → conflict → turning point → resolution. The most memorable shape.' },
    pyramid: { label: 'Pyramid (Minto)', hint: 'Answer first, then the reasons and the evidence. Best for executives.' },
    swot: { label: 'SWOT', hint: 'Strengths, weaknesses, opportunities, threats and the takeaway.' },
    'case-study': { label: 'Case study', hint: 'Context → what was done → measured result → lessons learned.' },
    academic: { label: 'Academic', hint: 'Intro → literature → method → findings → discussion → references.' },
    pitch: { label: 'Investor pitch', hint: 'Problem → solution → market → business model → team → ask.' },
    training: { label: 'Training', hint: 'Objectives → concepts → example → practice → summary → assessment.' },
    retrospective: { label: 'Review', hint: 'Goal → what was done → the numbers → what went well or badly → next period.' },
  } as Record<Framework, { label: string; hint: string }>,

  frameworkTitle: 'Content framework',
  frameworkSub: 'The narrative skeleton of the deck. You can see its sections below.',
  frameworkSections: 'Sections',

  media: {
    title: 'Visual',
    aiGenerate: 'Generate with AI',
    generating: 'Generating image…',
    prompt: 'What should the image show?',
    promptHint: 'Leave empty to use the slide title and content.',
    style: 'Visual style',
    styles: {
      photo: 'Photo',
      illustration: 'Illustration',
      flat: 'Flat vector',
      isometric: 'Isometric',
      minimal: 'Minimal',
      blueprint: 'Blueprint',
    },
    upload: 'Upload a file',
    uploadHint: 'PNG, JPG, WEBP or GIF · 800 KB max',
    remove: 'Remove image',
    replace: 'Replace',
    failed: 'Could not generate the image. Try again or upload your own file.',
    quota:
      'The free image service is out of quota right now. Try again in a few minutes or upload your own file.',
    tooLarge: 'The image is too large and could not be downscaled.',
    provider: 'A keyless free image service is used; the prompt is sent to that provider.',
    animatedNote: 'Animated GIF generation is not available on free providers — you can upload your own GIF.',
    placement: 'Placement',
    placements: {
      background: 'Background',
      band: 'Bottom strip',
      inset: 'Corner frame',
    },
    placementHints: {
      background: 'Covers the whole slide, with a scrim so the text stays readable.',
      band: 'A full-width strip below the body.',
      inset: 'A small right-aligned frame.',
    },
    fit: 'Frame fit',
    fits: { cover: 'Fill (crops)', contain: 'Fit (shows all)' },
    frame: 'Position the image in its frame',
    frameHint: 'Drag the image to change the focus, zoom with the wheel or the slider.',
    zoom: 'Zoom',
    reset: 'Reset',
    altLabel: 'Image description',
    altHint: 'For screen readers and the PPTX export. Can be left empty.',
  },

  format: {
    title: 'Text format',
    hint: 'Applies to all text on this slide. Colour and font follow the theme, so contrast is preserved.',
    font: 'Font',
    fonts: {
      theme: 'Theme font',
      sans: 'Sans (Inter)',
      serif: 'Serif (Georgia)',
      display: 'Display',
      mono: 'Monospace',
    },
    size: 'Size',
    smaller: 'Smaller',
    bigger: 'Larger',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    align: 'Alignment',
    aligns: { left: 'Left', center: 'Center', right: 'Right' },
    tone: 'Colour',
    tones: { default: 'Default', accent: 'Accent', muted: 'Muted' },
    lineHeight: 'Line spacing',
    reset: 'Reset format',
    resetHint: 'The slide returns to the theme’s own styling.',
  },

  glyphs: {
    idea: 'Idea',
    chart: 'Data',
    growth: 'Growth',
    users: 'People',
    gear: 'Process',
    shield: 'Security',
    cloud: 'Cloud',
    code: 'Code',
    target: 'Goal',
    clock: 'Time',
    book: 'Sources',
    money: 'Cost',
    warning: 'Risk',
    check: 'Approved',
    search: 'Research',
    globe: 'Global',
    rocket: 'Launch',
    network: 'Network',
    database: 'Database',
    mobile: 'Mobile',
    energy: 'Energy',
    health: 'Health',
    leaf: 'Sustainability',
    lock: 'Privacy',
    message: 'Communication',
    star: 'Quality',
    calendar: 'Calendar',
    layers: 'Layers',
    flask: 'Experiment',
    scale: 'Law / balance',
  },
}

export type SunumText = typeof TR

export function sunumText(lang: Lang): SunumText {
  return lang === 'en' ? EN : TR
}
