// Code Review arayüz metinleri (TR / EN). Motor metinleri için bkz. lib/codereview/i18n.ts.
import { crLang } from './i18n'

const UI = {
  tr: {
    appSub: 'AI + kural tabanlı kod inceleme — tarayıcıda',
    tabReview: 'İnceleme',
    tabReviewSub: 'MR’ı çek & incele',
    tabRules: 'Kurallar',
    tabRulesSub: 'md dosyaları & kurallar',

    browser: 'tarayıcı',
    logout: 'Çıkış',
    close: 'Kapat',
    cancel: 'Vazgeç',
    flowGitOut: ['diff', 'merge request'],
    flowGitIn: ['yorum', 'commit'],
    flowAiOut: ['kod', 'prompt'],
    flowAiIn: ['bulgu', 'analiz'],

    // --- AI bağlantısı ---
    aiTitle: '🤖 AI Bağlantısı',
    aiConnected: (model: string) => `${model} bağlı`,
    aiVerifying: 'doğrulanıyor…',
    aiNotConnected: 'bağlı değil (AI modları çalışmaz)',
    aiFlowConnected: (label: string) => `${label} bağlı`,
    aiFlowConnecting: (label: string) => `${label}’a bağlanılıyor…`,
    aiFlowDetailOff: 'bağlı değil — AI modları çalışmaz',
    aiDisconnect: 'Bağlantıyı Kes',
    aiConnectOther: 'Farklı AI Bağla',
    aiFreeKey: 'ücretsiz anahtar al',
    aiApiKey: 'API Key',
    aiKeyPh: 'anahtarı yapıştır',
    aiBaseUrl: 'Base URL',
    aiModel: 'Model',
    aiConnecting: 'Bağlanıyor & doğrulanıyor…',
    aiConnectWith: (label: string) => `${label} ile bağlan`,
    aiFootnote:
      'Bağlantı tarayıcıdan doğrulanır (başarısızsa neden gösterilir). Anahtar bu tarayıcıda hatırlanır. ' +
      'Tarayıcı CORS’u nedeniyle bazı sağlayıcılar/kurumsal servisler engellenebilir; en garantisi yerel Ollama.',
    aiProviderNotes: {
      ollama: 'Anahtarsız, ücretsiz. Tarayıcıdan erişim için Ollama’yı OLLAMA_ORIGINS=* ile başlat.',
      claude:
        'Anthropic Claude (ücretli API anahtarı). Model: claude-haiku-4-5 · claude-sonnet-4-6 · claude-opus-4-8. Tarayıcıdan doğrudan çağrılır.',
      gemini: 'Ücretsiz ama SIKI kotalı (429). Model: gemini-2.0-flash · gemini-2.0-flash-lite',
      groq: 'Ücretsiz, hızlı. Model: openai/gpt-oss-20b · qwen/qwen3-32b',
      openrouter: 'Ücretsiz (:free) modeller.',
      cerebras: 'Ücretsiz, hızlı.',
      mistral: 'Ücretsiz katman.',
      custom: 'OpenAI-uyumlu gateway / vLLM.',
    } as Record<string, string>,
    aiProviderLabels: { ollama: 'Ollama (yerel)', custom: 'Özel' } as Record<string, string>,

    // --- Git bağlantısı ---
    gitTitle: '🔗 Git Bağlantısı',
    gitConnected: (label: string) => `${label} bağlı`,
    gitConnecting: 'bağlanılıyor…',
    gitNotConnected: 'bağlı değil',
    gitFlowConnecting: (label: string) => `${label}’a bağlanılıyor…`,
    gitNoHost: 'sunucu adresi girilmedi',
    gitHostLabel: (label: string) => `${label} sunucu adresi`,
    gitUsername: 'Kullanıcı adı',
    gitUsernamePh: 'kullanıcı adı',
    gitUsernameOwnPh: 'kullanıcı adın',
    gitPassGitlab: 'Parola',
    gitPassGithub: 'Parola / Token',
    gitPassBitbucket: 'App Password',
    gitPassPhGitlab: 'parola',
    gitPassPhGithub: 'parola veya token',
    gitPassPhBitbucket: 'app password',
    gitLogin: '🔓 Giriş yap',
    gitLoggingIn: 'Giriş yapılıyor…',
    gitNoPlainPassword: (label: string, passLabel: string, tokenLabel: string) => (
      `${label} düz parolayı desteklemez; “${passLabel}” alanına ${tokenLabel} girin.`
    ),
    gitCreate: 'oluştur →',
    gitOrToken: '— veya doğrudan token ile —',
    gitTokenPh: 'token / app password',
    gitUse: 'Kullan',
    gitWriteScopeGitlab: 'api scope',
    gitWriteScopeGithub: 'repo izni',
    gitWriteScopeBitbucket: 'Pull requests: write',
    gitWriteNote: (req: string) => (
      `Yorum göndermek için erişimin yazma yetkili olmalı (${req}). Yetki yoksa gönderim sırasında token istenir. ` +
      `Kurumsal sunucu CORS’a takarsa token yolunu kullan.`
    ),

    // --- İnceleme sayfası ---
    reviewTitle: 'Kod İncelemesi',
    modesTitle: 'İnceleme modu',
    modes: {
      AI_WITH_RULES: {
        label: 'Yapay zeka + mevcut kurallar', short: 'Hibrit', tag: 'en kapsamlı',
        desc: 'Kural motoru ile AI birlikte çalışır: deterministik ihlaller + optimizasyon, performans ve mantık bulguları.',
      },
      RULES_ONLY: {
        label: 'Yalnızca mevcut kurallar', short: 'Deterministik', tag: '',
        desc: 'Sadece md kuralları; tarayıcıda satır satır denetlenir. Yapay zeka kullanılmaz, sonuç her seferinde aynıdır.',
      },
      AI_ONLY: {
        label: 'Yalnızca yapay zeka', short: 'Serbest', tag: '',
        desc: 'Sadece AI incelemesi: kod optimizasyonu, performans ve mantık hataları. Kurallara bakmaz.',
      },
    } as Record<string, { label: string; short: string; tag: string; desc: string }>,
    useRules: '⚙️ kurallar',
    useAi: '🤖 yapay zeka',
    useAiOff: ' · bağlı değil',
    gitboxTitle: (label: string, pr: string) => `${label} ${pr} linkinden incele`,
    gitboxUrl: (pr: string) => `${pr} URL`,
    reviewing: 'İnceleniyor…',
    fetchAndReview: (pr: string) => `${pr}’ı Çek ve İncele`,
    privateNote: (label: string) => `Private depo için önce yukarıdan ${label} bağlantısını yap (token oturumda kullanılır).`,
    fetchingDiff: (pr: string) => `${pr} diff'i çekiliyor…`,
    noChangedFiles: (pr: string) => `${pr}’da değişen dosya bulunamadı.`,
    sendCta: '📤 Bu değişiklikleri Git’e gönder',
    sendCtaNote: 'Seçtiğin bulgular MR’a yorum olarak eklenir ya da kaynak dala commit atılıp ilgili satırın üstüne TODO notu yazılır.',
    findingCount: (n: number) => `${n} bulgu`,
    badgeRule: 'KURAL',
    aiSuggestionPrefix: '🤖 AI önerisi: ',
    suggestionPrefix: '💡 Öneri: ',
    line: 'satır',

    // --- Git'e gönder paneli ---
    sendTitle: 'Git’e gönder',
    sendSubComment: 'Bulguları seç, seçtiklerin MR’a yorum olarak eklensin',
    sendSubCommit: 'Bulguları seç, kaynak dala commit atılıp ilgili satırın üstüne TODO yazılsın',
    sendModeComment: 'Yorum olarak gönder',
    sendModeCommentSub: (pr: string) => `${pr}’a not düşülür, kod değişmez`,
    sendModeCommit: 'Commit olarak gönder (TODO)',
    sendModeCommitSub: 'Kaynak dala commit; ilgili satırın üstüne TODO eklenir',
    selectAll: 'Tümünü seç',
    combineOne: 'Tek özet yorumda birleştir',
    commitHint: (pr: string) =>
      `Dosyalar ${pr}’ın kaynak dalından okunur, TODO satırları eklenir ve tek commit olarak aynı dala push edilir. ` +
      `Yorum sözdizimi dosya uzantısına göre seçilir. Commit öncesi özet gösterilir.`,
    commitHintNoLine: (n: number) => `⚠️ Seçilenlerden ${n} tanesinin satır bilgisi yok; bunlar atlanır.`,
    preparingCommit: 'Commit hazırlanıyor…',
    sending: 'Gönderiliyor…',
    commitSelected: (n: number) => `📝 Seçilenleri commit’le (${n})`,
    sendSelected: (n: number) => `📨 Seçilenleri gönder (${n})`,
    noTokenWarn: (tokenLabel: string) => `⚠️ Token yok — göndermek için yazma yetkili ${tokenLabel} gerekir.`,
    linkInvalid: 'Link geçersiz',
    confirmSendTitle: (label: string) => `${label}’a gönderilsin mi?`,
    confirmSendHtml: (n: number, pr: string, id: string, combined: boolean) =>
      `<b>${n}</b> bulgu <b>${pr} #${id}</b>’a ${combined ? 'tek bir özet yorum' : 'ayrı yorumlar'} olarak gönderilecek.`,
    yesSend: 'Evet, gönder',
    no: 'Hayır',
    combinedHeader: (n: number) => `## 🔍 Portal Code Review — ${n} bulgu`,
    authTitle: '🔑 Yetki gerekli — token ile doğrula',
    authCommentHtml: (tokenLabel: string) =>
      `Yorum göndermek için <b>yazma</b> yetkili bir ${tokenLabel} gir; girince <b>kaldığın yerden devam</b> edilir.`,
    authAlreadySent: (n: number) => `<br><small>${n} yorum zaten gönderildi, tekrar gönderilmeyecek.</small>`,
    authCommitHtml: (tokenLabel: string) => `Commit atmak için <b>yazma</b> yetkili bir ${tokenLabel} gir.`,
    authConfirm: 'Doğrula ve devam et',
    authConfirmRetry: 'Doğrula ve tekrar dene',
    authFooter: (tokenLabel: string) => `yazma yetkili ${tokenLabel} oluştur →`,
    authTokenRequired: 'Token gerekli',
    sendStopped: 'Gönderim durduruldu',
    sendStoppedHtml: (n: number) => `✅ ${n} yorum gönderildi, kalanı gönderilmedi.`,
    sentTitle: 'Gönderildi',
    sentHtml: (n: number) => `✅ <b>${n}</b> yorum MR’a eklendi.`,
    partialTitle: 'Kısmen gönderildi',
    partialHtml: (ok: number, fail: number, errs: string) =>
      `✅ ${ok} gönderildi · ❌ ${fail} başarısız.<br><small>${errs}</small>`,
    prepareFailed: 'Hazırlanamadı',
    noTodoTitle: 'Eklenecek TODO yok',
    noTodoSkipped: (n: number) => `Seçilen bulguların satır bilgisi yok ya da dosyada karşılığı bulunamadı (${n} bulgu).`,
    noTodoExisting: 'Bu TODO notları dosyalarda zaten mevcut görünüyor.',
    commitConfirmTitle: 'Commit atılsın mı?',
    commitBranch: 'Kaynak dal',
    commitSummary: (files: number, lines: number) =>
      `<b>${files}</b> dosyaya toplam <b>${lines}</b> satır TODO notu eklenecek:`,
    commitRow: (n: number) => `<b>${n}</b> TODO satırı`,
    commitSkipped: (n: number) => `⚠️ Satır bilgisi olmayan ${n} bulgu atlandı.`,
    commitMessageLabel: 'Commit mesajı',
    commitMessageRequired: 'Commit mesajı gerekli',
    yesCommit: 'Evet, commit at',
    commitDoneTitle: 'Commit atıldı',
    commitDoneHtml: (branch: string) => `✅ <b>${branch}</b> dalına commit atıldı.`,
    commitOpen: 'commit’i aç →',
    commitFailed: 'Commit atılamadı',
    commentSuggestion: 'Öneri',
    commentRule: '⚙️ Kural',

    // --- Özet & istatistik ---
    summaryTitle: '📋 İnceleme Özeti',
    summaryMeta: (n: number) => `${n} dosya · mod: `,
    total: 'toplam',
    rules: 'kural',
    findingsWord: 'bulgu',
    filesWithFindings: (touched: number, all: number) => `${touched}/${all} dosyada bulgu`,
    blockerish: 'engelleyici/kritik',
    perFile: 'bulgu/dosya',
    sevDistribution: 'Önem dağılımı',
    findingsPerFile: 'Dosya bazında bulgular',
    onlySev: (s: string) => `Yalnızca ${s} bulguları göster`,
    onlyRuleFindings: 'Yalnızca kural bulguları',
    onlyAiFindings: 'Yalnızca AI bulguları',
    onlyThisFile: (p: string) => `${p} — yalnızca bu dosyanın bulguları`,
    filterPrefix: '🔎 Filtre: ',
    filterShowing: (shown: number, all: number) => `${shown}/${all} bulgu gösteriliyor`,
    clearFilter: 'filtreyi temizle',
    filterSev: (v: string) => `önem: ${v}`,
    filterSrcAi: 'kaynak: AI',
    filterSrcRule: 'kaynak: kural',
    filterFile: (v: string) => `dosya: ${v}`,
    noFindings: 'Seçilen moda göre bulgu bulunamadı. ✅',
    seeDetails: 'Detayları gör',

    // --- Bulgu detayı ---
    fdTitle: 'Bulgu detayı',
    fdLocation: 'Konum',
    fdFileLevel: 'dosya düzeyi',
    fdFinding: 'Bulgu',
    fdSuggestion: 'Öneri',
    fdMatchedCode: 'Denk geldiği kod',
    fdWholeFile: 'Bu bulgu tek bir satıra değil, dosyanın tamamına ait.',
    fdNotInDiff: 'Bu satır diff’in eklenen satırları arasında bulunamadı.',
    fdProducedBy: 'Bu bulguyu üreten kural',

    // --- Yükleme ekranı ---
    loaderAiOnly: 'AI Tabanlı İnceleme',
    loaderAiOnlySub: 'Yapay zeka incelemesi',
    loaderHybrid: 'AI + Kural İncelemesi',
    loaderHybridSub: 'Yapay zeka ve kurallar birlikte',
    loaderRules: 'Kural Tabanlı İnceleme',
    loaderRulesSub: 'Deterministik kurallar',
    loaderMsgFetch: '📥 Diff okunuyor…',
    loaderMsgRules: '📐 Kurallar uygulanıyor…',
    loaderMsgScan: '🔎 Satırlar taranıyor…',
    loaderMsgAi: '🧠 Yapay zeka kodu analiz ediyor…',
    loaderMsgFind: '🧾 Bulgular derleniyor…',
    loaderMsgSug: '💡 Öneriler hazırlanıyor…',
    loaderFiles: (done: number, total: number, pct: number) => `${done}/${total} dosya · %${pct}`,
    loaderVariable: 'süre değişkendir',

    // --- Kural rehberi ---
    guideTitle: 'Nasıl kural eklenir?',
    guideSub: 'Kurallar deterministik çalışır — yapay zeka kullanılmaz',
    guideTabStart: 'Başla',
    guideTabStartSub: 'kural nasıl eklenir',
    guideTabPattern: 'Desen ekle',
    guideTabPatternSub: 'soyut kuralı otomatiğe çevir',
    guideTabExamples: 'Örnekler',
    guideTabExamplesSub: 'hazır kalıplar',
    guideStep1: 'Formu doldur',
    guideStep1Sub: 'Ad, tip, önem, dosya deseni ve gövdeyi gir.',
    guideStep2: 'Hedef md seç',
    guideStep2Sub: 'Kural konusuna uygun dosyayı seç (ör. react, spring).',
    guideStep3: 'Ekle',
    guideStep3Sub: 'Kural anında listeye ve incelemeye dahil olur.',
    guideRegexHead: 'REGEX ile eşleştir',
    guideRegexBody: 'Kendi düzenli ifadeni yazarsın; eşleşen her satır bulgu olur. En hassas yol.',
    guideTextHead: 'Düz dille yaz',
    guideTextBody: 'Kuralı normal cümleyle yazarsın; içindeki anahtar kelime yerleşik bir dedektöre bağlanır ve otomatik denetlenir.',
    guideBody: 'Gövde',
    guideTextBodyEx: 'Kodda yorum satırı olmamalı',
    guideKwTitle: '⚙️ Otomatik denetime bağlayan anahtar kelimeler',
    guideKwNote: 'Bu kelimelerden birini içermeyen genel kurallar ✋ Elle olarak işaretlenir — “Desen ekle” sekmesindeki ekle bunları da otomatiğe çevirebilirsin.',
    guideLead: 'Kuralın tipini değiştirmeden, metnin sonuna açık bir desen yazarsın. Tahmin yoktur; yalnızca yazdığın desen çalışır.',
    // Örnek kural gövdeleri — motor hem "Yasak:/Zorunlu:" hem "Forbidden:/Required:" tanır.
    guideForbidEx: 'Bileşende inline style kullanılmaz. Yasak: ',
    guideRequireEx: 'Her test describe ile başlar. Zorunlu: ',
    guideLimitEx: 'Bileşen en fazla 300 satır olmalı',
    fixExForbidden: '… Yasak: ',
    fixExRequired: '… Zorunlu: ',
    guideForbidHead: 'Yasak: eşleşen satır ihlaldir',
    guideForbidNote: 'Diff’te eklenen satırlardan biri desene uyarsa bulgu üretilir.',
    guideRequireHead: 'Zorunlu: hiç eşleşme yoksa ihlaldir',
    guideRequireNote: 'Dosyanın eklenen satırlarının hiçbiri uymuyorsa bulgu üretilir. Yanlış pozitife açıktır — dikkatli kullanın.',
    guideLimitHead: 'Sınır: ölçülebilir üst sınır',
    guideLimitNote: '“en fazla / < / aşmamalı” + sayı → dosya uzunluğu diff üzerinden ölçülür.',
    guideWarnTitle: '⚠️ Desen yazarken',
    guideWarn1: 'Desen içinde backtick ve ** kullanma — metin temizliğinde silinir, regex bozulur.',
    guideWarn2: 'dizilimi oluşturma — markdown bağlantısı sanılıp yenir.',
    guideWarn3: 'karakterini kaçır; bayrak (flag) yazma.',
    guideWarn4: 'Neredeyse her satıra uyan desen, denetimsiz kuraldan kötüdür — o durumda kuralı elle bırak.',
    guideExamples: [
      { type: 'LLM', pattern: '**', name: 'Yorum satırı yasak', body: 'Gövde: “Kodda yorum satırı olmamalı” → tüm // ve /* */ yakalanır' },
      { type: 'REGEX', pattern: '*.tsx', name: 'console.log yasak', body: 'Gövde: console\\.log' },
      { type: 'LLM', pattern: '*.java', name: 'System.out yasak', body: 'Gövde: “System.out ile loglama yapılmamalı”' },
      { type: 'LLM', pattern: '*.tsx', name: 'Inline style yasak', body: 'Gövde: “Inline style kullanılmaz. Yasak: /style=\\{\\{/”' },
      { type: 'LLM', pattern: '*.java', name: 'Field injection yasak', body: 'Gövde: “Constructor injection kullanılmalı. Yasak: /@Autowired\\b/”' },
      { type: 'LLM', pattern: '*.tsx', name: 'Bileşen boyutu', body: 'Gövde: “Bileşen en fazla 300 satır olmalı” → Sınır denetimi' },
    ] as { type: string; pattern: string; name: string; body: string }[],
    guideFoot: 'Kural dosyaları: rules-md/*.md · biçim ayrıntıları için rules-md/README.md',
    guideOk: 'Anladım',
    badgePattern: 'Desen',
    badgeText: 'Metin',

    // --- Kural detayı ---
    ruleDetailTitle: 'Kural detayı',
    rdWhatSays: 'Kural ne diyor?',
    rdStatus: 'Denetim durumu',
    rdChecksOne: 'Çalışan denetim',
    rdChecksMany: 'Çalışan denetimler',
    rdCopy: '⧉ kopyala',
    rdCopied: '✓ kopyalandı',
    rdHowFix: 'Nasıl denetlenebilir yapılır?',
    rdScope: 'Kapsam',
    rdFilePattern: 'Dosya deseni',
    rdSeverity: 'Önem',
    rdType: 'Tip',
    rdState: 'Durum',
    rdActive: '● aktif',
    rdInactive: '○ pasif',
    rdSource: 'Kaynak',
    rdPipeline: 'md satırından kurala',
    rdHideSteps: 'adımları gizle',
    rdShowSteps: 'adımları göster',
    rdRawLine: 'HAM SATIR',
    rdCleanBody: 'İŞLENMİŞ GÖVDE',
    rdCleanNote: 'Motorun sakladığı metin; desen ekleri burada durur.',
    rdFinalMsg: 'BULGUDA GÖRÜNEN MESAJ',
    rdFinalNote: 'Bir ihlal bulunduğunda incelemede bu metin gösterilir.',
    rdNameFrom: 'Ad nereden',
    rdSevFrom: 'Önem nereden',
    rdPatternFrom: 'Dosya deseni nereden',
    rdExamples: 'Bu kural nasıl bulguya girer?',
    rdMoveToProbe: 'Canlı denemeye taşı',
    rdExamplesNote:
      'Örnek satırlar kuralın kendi deseninden türetilir ve gerçek desenle doğrulanır — gerçek kodun birebir hali değil, desenin neyi yakaladığının en sade göstergesidir.',
    rdProbe: 'Canlı deneme',
    rdProbePh: 'Bir kod satırı yapıştırın…',
    rdProbeFires: '⛔ Bulgu üretir',
    rdProbeClean: '✓ Bulgu üretmez',
    rdEdit: '✏ Düzenle',
    rdDisable: 'Pasifleştir',
    rdEnable: 'Aktifleştir',
    rdDelete: 'Sil',

    // --- Kapsam istatistikleri ---
    coverRingTitle: (n: number) => `${n} kural makine ile denetleniyor — listeyi filtrelemek için tıkla`,
    coverAuto: 'otomatik',
    coverRules: 'kural',
    coverMachine: 'makine',
    coverManual: 'elle',
    coverAllAuto: 'Tüm kurallar makine ile denetleniyor.',
    coverNote: (n: number) =>
      `Kalan ${n} kural soyut (dosya konumu, kod tekrarı, katmanlar arası tutarlılık gibi) — tek satırdan denetlenemez, insan incelemesi gerekir.`,
    coverMeta: {
      REGEX: { label: '⚙️ Regex', short: 'Regex', title: 'Kuralın kendi düzenli ifadesiyle satır satır denetlenir.' },
      PATTERN: { label: '⚙️ Desen', short: 'Desen', title: 'Kural metnine yazılmış "Yasak:" / "Zorunlu:" deseniyle denetlenir.' },
      DETECTOR: { label: '⚙️ Yerleşik', short: 'Yerleşik', title: 'Kural metni yerleşik bir dedektöre bağlandı; satır satır denetlenir.' },
      LIMIT: { label: '⚙️ Sınır', short: 'Sınır', title: 'Kuraldaki satır üst sınırı diff üzerinden ölçülerek denetlenir.' },
      MANUAL: { label: '✋ Elle', short: 'Elle', title: 'Soyut kural — makine ile denetlenemez. Kural metnine "Yasak:/Zorunlu:" deseni ekleyin.' },
    } as Record<string, { label: string; short: string; title: string }>,

    // --- Kurallar sayfası ---
    rulesHeroTitle: 'Kurallar & md Dosyaları',
    rulesHeroSub: 'Kurallar projedeki rules-md/*.md dosyalarından okunur; değişiklikler tarayıcıda saklanır.',
    guideClose: '✕ Rehberi kapat',
    guideOpen: '💡 Nasıl kural eklenir?',
    mdUpdated: (n: number) => `Projede ${n} kural dosyası güncellendi`,
    mdUpdatedNote: 'Tarayıcıdaki kopyanız düzenlenmiş olduğu için otomatik güncellenmedi: ',
    mdUpdate: 'Güncelle',
    mdUpdatedOk: (n: number) => `✅ ${n} dosya projedeki sürümle güncellendi.`,
    segRules: '⚙️ Kurallar',
    segFiles: '📄 md Dosyaları',
    refresh: '↻ Yenile',
    newRule: 'Yeni Kural',
    editRule: 'Kuralı Düzenle',
    fName: 'Ad',
    fDescription: 'Açıklama',
    fType: 'Tip',
    fSeverity: 'Önem',
    fFilePattern: 'Dosya deseni',
    fBody: 'Gövde (REGEX deseni / LLM talimatı)',
    fTargetMd: 'Hedef md dosyası',
    fEnabled: 'Aktif',
    add: 'Ekle',
    update: 'Güncelle',
    cancelBtn: 'İptal',
    ruleSaveNeeds: '⚠️ Ad, gövde ve hedef md gerekli.',
    ruleSaved: (file: string) => `✅ Kural '${file}' dosyasına yazıldı.`,
    search: 'Ara',
    searchPh: 'ad / gövde / dosya',
    sourceMd: 'Kaynak md',
    all: 'Tümü',
    checking: 'Denetim',
    autoAll: '⚙️ Otomatik (hepsi)',
    coverHint:
      'Bu kurallar soyut olduğu için makine ile denetlenemiyor. Denetlenebilir yapmak için kural metninin sonuna açık bir desen ekleyin: ',
    coverHintForbid: ' (eşleşen satır ihlaldir) veya ',
    coverHintRequire: ' (dosyada hiç eşleşme yoksa ihlaldir).',
    ruleInactive: 'pasif',
    noRulesAtAll: 'md dosyalarında kural yok.',
    noRulesMatch: 'Filtreye uyan kural yok.',
    areaFrontend: 'Frontend',
    areaBackend: 'Backend',
    areaGeneral: 'Genel',
    mdFiles: 'md Dosyaları',
    newMdFile: 'Yeni md dosyası',
    create: 'Oluştur',
    resetFromProject: '↻ Projedekilerden sıfırla',
    createdOk: (name: string) => `✅ '${name}' oluşturuldu.`,
    updatedOk: (name: string) => `✅ '${name}' güncellendi.`,
    resetOk: '↻ Projedeki md dosyalarından yeniden yüklendi.',
    view: '👁 Görüntüle',
    edit: '✏ Düzenle',
    save: 'Kaydet',
    download: '⬇ İndir',
    deleteBtn: 'Sil',
    editHint: 'Düzenlemek için ✏ Düzenle’ye geç.',
    savedInBrowser: 'Değişiklikler tarayıcıda saklanır.',
    permanentHint: (file: string) => ` Projeye kalıcı almak için İndir → src/rules-md/${file} ile değiştir.`,
    pickFileHint: 'Düzenlemek için soldan bir md dosyası seç ya da yeni dosya oluştur.',
    confirmDeleteFile: (name: string) => `'${name}' silinsin mi? (tarayıcı kopyası)`,
    confirmResetAll: 'Tüm md değişiklikleri silinip projedeki dosyalardan yeniden yüklensin mi?',
  },

  en: {
    appSub: 'AI + rule-based code review — in your browser',
    tabReview: 'Review',
    tabReviewSub: 'fetch & review the MR',
    tabRules: 'Rules',
    tabRulesSub: 'md files & rules',

    browser: 'browser',
    logout: 'Sign out',
    close: 'Close',
    cancel: 'Cancel',
    flowGitOut: ['diff', 'merge request'],
    flowGitIn: ['comment', 'commit'],
    flowAiOut: ['code', 'prompt'],
    flowAiIn: ['finding', 'analysis'],

    aiTitle: '🤖 AI Connection',
    aiConnected: (model: string) => `${model} connected`,
    aiVerifying: 'verifying…',
    aiNotConnected: 'not connected (AI modes will not run)',
    aiFlowConnected: (label: string) => `${label} connected`,
    aiFlowConnecting: (label: string) => `connecting to ${label}…`,
    aiFlowDetailOff: 'not connected — AI modes will not run',
    aiDisconnect: 'Disconnect',
    aiConnectOther: 'Connect a different AI',
    aiFreeKey: 'get a free key',
    aiApiKey: 'API Key',
    aiKeyPh: 'paste your key',
    aiBaseUrl: 'Base URL',
    aiModel: 'Model',
    aiConnecting: 'Connecting & verifying…',
    aiConnectWith: (label: string) => `Connect with ${label}`,
    aiFootnote:
      'The connection is verified from the browser (the reason is shown on failure). The key is remembered in this browser. ' +
      'Browser CORS may block some providers/corporate services; a local Ollama is the safest bet.',
    aiProviderNotes: {
      ollama: 'No key, free. Start Ollama with OLLAMA_ORIGINS=* so the browser can reach it.',
      claude:
        'Anthropic Claude (paid API key). Models: claude-haiku-4-5 · claude-sonnet-4-6 · claude-opus-4-8. Called directly from the browser.',
      gemini: 'Free but TIGHTLY rate-limited (429). Models: gemini-2.0-flash · gemini-2.0-flash-lite',
      groq: 'Free and fast. Models: openai/gpt-oss-20b · qwen/qwen3-32b',
      openrouter: 'Free (:free) models.',
      cerebras: 'Free and fast.',
      mistral: 'Free tier.',
      custom: 'OpenAI-compatible gateway / vLLM.',
    } as Record<string, string>,
    aiProviderLabels: { ollama: 'Ollama (local)', custom: 'Custom' } as Record<string, string>,

    gitTitle: '🔗 Git Connection',
    gitConnected: (label: string) => `${label} connected`,
    gitConnecting: 'connecting…',
    gitNotConnected: 'not connected',
    gitFlowConnecting: (label: string) => `connecting to ${label}…`,
    gitNoHost: 'no server address entered',
    gitHostLabel: (label: string) => `${label} server address`,
    gitUsername: 'Username',
    gitUsernamePh: 'username',
    gitUsernameOwnPh: 'your username',
    gitPassGitlab: 'Password',
    gitPassGithub: 'Password / Token',
    gitPassBitbucket: 'App Password',
    gitPassPhGitlab: 'password',
    gitPassPhGithub: 'password or token',
    gitPassPhBitbucket: 'app password',
    gitLogin: '🔓 Sign in',
    gitLoggingIn: 'Signing in…',
    gitNoPlainPassword: (label: string, passLabel: string, tokenLabel: string) => (
      `${label} does not accept a plain password; enter a ${tokenLabel} in the “${passLabel}” field.`
    ),
    gitCreate: 'create →',
    gitOrToken: '— or straight with a token —',
    gitTokenPh: 'token / app password',
    gitUse: 'Use',
    gitWriteScopeGitlab: 'api scope',
    gitWriteScopeGithub: 'repo permission',
    gitWriteScopeBitbucket: 'Pull requests: write',
    gitWriteNote: (req: string) => (
      `Your access must have write permission to post comments (${req}). Without it, a token is requested while sending. ` +
      `If a corporate server trips over CORS, use the token path.`
    ),

    reviewTitle: 'Code Review',
    modesTitle: 'Review mode',
    modes: {
      AI_WITH_RULES: {
        label: 'AI + existing rules', short: 'Hybrid', tag: 'most thorough',
        desc: 'The rule engine and the AI work together: deterministic violations plus optimization, performance and logic findings.',
      },
      RULES_ONLY: {
        label: 'Existing rules only', short: 'Deterministic', tag: '',
        desc: 'Only the md rules, checked line by line in the browser. No AI is used and the result is identical every time.',
      },
      AI_ONLY: {
        label: 'AI only', short: 'Free-form', tag: '',
        desc: 'AI review only: code optimization, performance and logic bugs. It ignores the rules.',
      },
    } as Record<string, { label: string; short: string; tag: string; desc: string }>,
    useRules: '⚙️ rules',
    useAi: '🤖 AI',
    useAiOff: ' · not connected',
    gitboxTitle: (label: string, pr: string) => `Review from a ${label} ${pr} link`,
    gitboxUrl: (pr: string) => `${pr} URL`,
    reviewing: 'Reviewing…',
    fetchAndReview: (pr: string) => `Fetch & Review the ${pr}`,
    privateNote: (label: string) => `For a private repo, connect ${label} above first (the token is used for the session).`,
    fetchingDiff: (pr: string) => `Fetching the ${pr} diff…`,
    noChangedFiles: (pr: string) => `No changed files found in the ${pr}.`,
    sendCta: '📤 Send these changes to Git',
    sendCtaNote: 'The findings you pick are added to the MR as comments, or committed to the source branch with a TODO note above the relevant line.',
    findingCount: (n: number) => `${n} findings`,
    badgeRule: 'RULE',
    aiSuggestionPrefix: '🤖 AI suggestion: ',
    suggestionPrefix: '💡 Suggestion: ',
    line: 'line',

    sendTitle: 'Send to Git',
    sendSubComment: 'Pick the findings you want added to the MR as comments',
    sendSubCommit: 'Pick the findings; a commit adds a TODO above each relevant line on the source branch',
    sendModeComment: 'Send as comments',
    sendModeCommentSub: (pr: string) => `A note is left on the ${pr}; the code is untouched`,
    sendModeCommit: 'Send as a commit (TODO)',
    sendModeCommitSub: 'Commit to the source branch; a TODO is added above the relevant line',
    selectAll: 'Select all',
    combineOne: 'Combine into one summary comment',
    commitHint: (pr: string) =>
      `Files are read from the ${pr}'s source branch, TODO lines are inserted and pushed back to the same branch as a single commit. ` +
      `The comment syntax is chosen by file extension. A summary is shown before committing.`,
    commitHintNoLine: (n: number) => `⚠️ ${n} of the selected findings have no line info; those are skipped.`,
    preparingCommit: 'Preparing the commit…',
    sending: 'Sending…',
    commitSelected: (n: number) => `📝 Commit selected (${n})`,
    sendSelected: (n: number) => `📨 Send selected (${n})`,
    noTokenWarn: (tokenLabel: string) => `⚠️ No token — sending requires a ${tokenLabel} with write permission.`,
    linkInvalid: 'Invalid link',
    confirmSendTitle: (label: string) => `Send to ${label}?`,
    confirmSendHtml: (n: number, pr: string, id: string, combined: boolean) =>
      `<b>${n}</b> findings will be sent to <b>${pr} #${id}</b> as ${combined ? 'a single summary comment' : 'separate comments'}.`,
    yesSend: 'Yes, send',
    no: 'No',
    combinedHeader: (n: number) => `## 🔍 Portal Code Review — ${n} findings`,
    authTitle: '🔑 Permission required — verify with a token',
    authCommentHtml: (tokenLabel: string) =>
      `Enter a ${tokenLabel} with <b>write</b> permission to post comments; sending <b>resumes where it stopped</b>.`,
    authAlreadySent: (n: number) => `<br><small>${n} comments were already sent and will not be sent again.</small>`,
    authCommitHtml: (tokenLabel: string) => `Enter a ${tokenLabel} with <b>write</b> permission to commit.`,
    authConfirm: 'Verify and continue',
    authConfirmRetry: 'Verify and try again',
    authFooter: (tokenLabel: string) => `create a ${tokenLabel} with write permission →`,
    authTokenRequired: 'Token required',
    sendStopped: 'Sending stopped',
    sendStoppedHtml: (n: number) => `✅ ${n} comments sent; the rest were not.`,
    sentTitle: 'Sent',
    sentHtml: (n: number) => `✅ <b>${n}</b> comments added to the MR.`,
    partialTitle: 'Partially sent',
    partialHtml: (ok: number, fail: number, errs: string) =>
      `✅ ${ok} sent · ❌ ${fail} failed.<br><small>${errs}</small>`,
    prepareFailed: 'Could not prepare',
    noTodoTitle: 'No TODO to add',
    noTodoSkipped: (n: number) => `The selected findings have no line info or no match in the file (${n} findings).`,
    noTodoExisting: 'These TODO notes already appear to be present in the files.',
    commitConfirmTitle: 'Create the commit?',
    commitBranch: 'Source branch',
    commitSummary: (files: number, lines: number) =>
      `<b>${lines}</b> TODO lines will be added across <b>${files}</b> files:`,
    commitRow: (n: number) => `<b>${n}</b> TODO lines`,
    commitSkipped: (n: number) => `⚠️ ${n} findings without line info were skipped.`,
    commitMessageLabel: 'Commit message',
    commitMessageRequired: 'A commit message is required',
    yesCommit: 'Yes, commit',
    commitDoneTitle: 'Commit created',
    commitDoneHtml: (branch: string) => `✅ Committed to the <b>${branch}</b> branch.`,
    commitOpen: 'open the commit →',
    commitFailed: 'Could not commit',
    commentSuggestion: 'Suggestion',
    commentRule: '⚙️ Rule',

    summaryTitle: '📋 Review Summary',
    summaryMeta: (n: number) => `${n} files · mode: `,
    total: 'total',
    rules: 'rules',
    findingsWord: 'findings',
    filesWithFindings: (touched: number, all: number) => `findings in ${touched}/${all} files`,
    blockerish: 'blocker/critical',
    perFile: 'findings/file',
    sevDistribution: 'Severity distribution',
    findingsPerFile: 'Findings per file',
    onlySev: (s: string) => `Show only ${s} findings`,
    onlyRuleFindings: 'Only rule findings',
    onlyAiFindings: 'Only AI findings',
    onlyThisFile: (p: string) => `${p} — only this file's findings`,
    filterPrefix: '🔎 Filter: ',
    filterShowing: (shown: number, all: number) => `showing ${shown}/${all} findings`,
    clearFilter: 'clear filter',
    filterSev: (v: string) => `severity: ${v}`,
    filterSrcAi: 'source: AI',
    filterSrcRule: 'source: rule',
    filterFile: (v: string) => `file: ${v}`,
    noFindings: 'No findings for the selected mode. ✅',
    seeDetails: 'See details',

    fdTitle: 'Finding detail',
    fdLocation: 'Location',
    fdFileLevel: 'file level',
    fdFinding: 'Finding',
    fdSuggestion: 'Suggestion',
    fdMatchedCode: 'Matched code',
    fdWholeFile: 'This finding belongs to the whole file, not a single line.',
    fdNotInDiff: "This line was not found among the diff's added lines.",
    fdProducedBy: 'The rule that produced this finding',

    loaderAiOnly: 'AI-Based Review',
    loaderAiOnlySub: 'AI review',
    loaderHybrid: 'AI + Rule Review',
    loaderHybridSub: 'AI and rules together',
    loaderRules: 'Rule-Based Review',
    loaderRulesSub: 'Deterministic rules',
    loaderMsgFetch: '📥 Reading the diff…',
    loaderMsgRules: '📐 Applying the rules…',
    loaderMsgScan: '🔎 Scanning the lines…',
    loaderMsgAi: '🧠 The AI is analysing the code…',
    loaderMsgFind: '🧾 Compiling findings…',
    loaderMsgSug: '💡 Preparing suggestions…',
    loaderFiles: (done: number, total: number, pct: number) => `${done}/${total} files · ${pct}%`,
    loaderVariable: 'duration varies',

    guideTitle: 'How do I add a rule?',
    guideSub: 'Rules run deterministically — no AI involved',
    guideTabStart: 'Start',
    guideTabStartSub: 'how to add a rule',
    guideTabPattern: 'Add a pattern',
    guideTabPatternSub: 'turn an abstract rule automatic',
    guideTabExamples: 'Examples',
    guideTabExamplesSub: 'ready-made recipes',
    guideStep1: 'Fill the form',
    guideStep1Sub: 'Enter the name, type, severity, file pattern and body.',
    guideStep2: 'Pick a target md',
    guideStep2Sub: 'Choose the file that matches the rule topic (e.g. react, spring).',
    guideStep3: 'Add',
    guideStep3Sub: 'The rule joins the list and the review immediately.',
    guideRegexHead: 'Match with REGEX',
    guideRegexBody: 'You write your own regular expression; every matching line becomes a finding. The most precise path.',
    guideTextHead: 'Write in plain language',
    guideTextBody: 'You write the rule as an ordinary sentence; a keyword inside it binds to a built-in detector and is checked automatically.',
    guideBody: 'Body',
    guideTextBodyEx: 'Code must contain no comments',
    guideKwTitle: '⚙️ Keywords that bind a rule to automatic checking',
    guideKwNote: 'General rules containing none of these words are marked ✋ Manual — the "Add a pattern" tab shows how to make those automatic too.',
    guideLead: 'Without changing the rule type, you append an explicit pattern to the end of the text. Nothing is guessed; only the pattern you wrote runs.',
    // Sample rule bodies — the engine accepts both "Yasak:/Zorunlu:" and "Forbidden:/Required:".
    guideForbidEx: 'No inline styles in components. Forbidden: ',
    guideRequireEx: 'Every test starts with describe. Required: ',
    guideLimitEx: 'A component must be at most 300 lines',
    fixExForbidden: '… Forbidden: ',
    fixExRequired: '… Required: ',
    guideForbidHead: 'Forbidden: a matching line is a violation',
    guideForbidNote: 'If one of the added lines in the diff matches the pattern, a finding is produced.',
    guideRequireHead: 'Required: no match at all is a violation',
    guideRequireNote: "If none of the file's added lines match, a finding is produced. Prone to false positives — use with care.",
    guideLimitHead: 'Limit: a measurable upper bound',
    guideLimitNote: '"at most / < / must not exceed" + a number → file length is measured from the diff.',
    guideWarnTitle: '⚠️ When writing a pattern',
    guideWarn1: 'Do not use backticks or ** inside the pattern — text cleanup strips them and breaks the regex.',
    guideWarn2: 'do not form this sequence — it is mistaken for a markdown link and eaten.',
    guideWarn3: 'escape this character; do not write flags.',
    guideWarn4: 'A pattern that matches almost every line is worse than an unchecked rule — leave the rule manual in that case.',
    guideExamples: [
      { type: 'LLM', pattern: '**', name: 'No comments', body: 'Body: “Code must contain no comments” → all // and /* */ are caught' },
      { type: 'REGEX', pattern: '*.tsx', name: 'No console.log', body: 'Body: console\\.log' },
      { type: 'LLM', pattern: '*.java', name: 'No System.out', body: 'Body: “Do not log with System.out”' },
      { type: 'LLM', pattern: '*.tsx', name: 'No inline styles', body: 'Body: “No inline styles. Forbidden: /style=\\{\\{/”' },
      { type: 'LLM', pattern: '*.java', name: 'No field injection', body: 'Body: “Use constructor injection. Forbidden: /@Autowired\\b/”' },
      { type: 'LLM', pattern: '*.tsx', name: 'Component size', body: 'Body: “A component must be at most 300 lines” → Limit check' },
    ] as { type: string; pattern: string; name: string; body: string }[],
    guideFoot: 'Rule files: rules-md/*.md · see rules-md/README.md for format details',
    guideOk: 'Got it',
    badgePattern: 'Pattern',
    badgeText: 'Text',

    ruleDetailTitle: 'Rule detail',
    rdWhatSays: 'What does the rule say?',
    rdStatus: 'Checking status',
    rdChecksOne: 'Active check',
    rdChecksMany: 'Active checks',
    rdCopy: '⧉ copy',
    rdCopied: '✓ copied',
    rdHowFix: 'How do I make it checkable?',
    rdScope: 'Scope',
    rdFilePattern: 'File pattern',
    rdSeverity: 'Severity',
    rdType: 'Type',
    rdState: 'State',
    rdActive: '● active',
    rdInactive: '○ inactive',
    rdSource: 'Source',
    rdPipeline: 'From md line to rule',
    rdHideSteps: 'hide steps',
    rdShowSteps: 'show steps',
    rdRawLine: 'RAW LINE',
    rdCleanBody: 'PROCESSED BODY',
    rdCleanNote: 'The text the engine stores; pattern suffixes live here.',
    rdFinalMsg: 'MESSAGE SHOWN IN THE FINDING',
    rdFinalNote: 'This text is shown in the review when a violation is found.',
    rdNameFrom: 'Name from',
    rdSevFrom: 'Severity from',
    rdPatternFrom: 'File pattern from',
    rdExamples: 'How does this rule turn into a finding?',
    rdMoveToProbe: 'Move to the live probe',
    rdExamplesNote:
      "The sample lines are derived from the rule's own pattern and verified against the real pattern — they are not literal production code, just the simplest illustration of what the pattern catches.",
    rdProbe: 'Live probe',
    rdProbePh: 'Paste a line of code…',
    rdProbeFires: '⛔ Produces a finding',
    rdProbeClean: '✓ No finding',
    rdEdit: '✏ Edit',
    rdDisable: 'Disable',
    rdEnable: 'Enable',
    rdDelete: 'Delete',

    coverRingTitle: (n: number) => `${n} rules are machine-checked — click to filter the list`,
    coverAuto: 'automatic',
    coverRules: 'rules',
    coverMachine: 'machine',
    coverManual: 'manual',
    coverAllAuto: 'All rules are machine-checked.',
    coverNote: (n: number) =>
      `The remaining ${n} rules are abstract (file placement, code duplication, cross-layer consistency and the like) — they cannot be checked from a single line and need human review.`,
    coverMeta: {
      REGEX: { label: '⚙️ Regex', short: 'Regex', title: "Checked line by line with the rule's own regular expression." },
      PATTERN: { label: '⚙️ Pattern', short: 'Pattern', title: 'Checked with the "Forbidden:" / "Required:" pattern written into the rule text.' },
      DETECTOR: { label: '⚙️ Built-in', short: 'Built-in', title: 'The rule text was bound to a built-in detector; checked line by line.' },
      LIMIT: { label: '⚙️ Limit', short: 'Limit', title: "The rule's line upper bound is measured from the diff." },
      MANUAL: { label: '✋ Manual', short: 'Manual', title: 'Abstract rule — cannot be machine-checked. Add a "Forbidden:/Required:" pattern to the rule text.' },
    } as Record<string, { label: string; short: string; title: string }>,

    rulesHeroTitle: 'Rules & md Files',
    rulesHeroSub: "Rules are read from the project's rules-md/*.md files; your changes are stored in the browser.",
    guideClose: '✕ Close the guide',
    guideOpen: '💡 How do I add a rule?',
    mdUpdated: (n: number) => `${n} rule files were updated in the project`,
    mdUpdatedNote: 'Your browser copy was edited, so it was not updated automatically: ',
    mdUpdate: 'Update',
    mdUpdatedOk: (n: number) => `✅ ${n} files updated with the project version.`,
    segRules: '⚙️ Rules',
    segFiles: '📄 md Files',
    refresh: '↻ Refresh',
    newRule: 'New Rule',
    editRule: 'Edit Rule',
    fName: 'Name',
    fDescription: 'Description',
    fType: 'Type',
    fSeverity: 'Severity',
    fFilePattern: 'File pattern',
    fBody: 'Body (REGEX pattern / LLM instruction)',
    fTargetMd: 'Target md file',
    fEnabled: 'Enabled',
    add: 'Add',
    update: 'Update',
    cancelBtn: 'Cancel',
    ruleSaveNeeds: '⚠️ Name, body and target md are required.',
    ruleSaved: (file: string) => `✅ The rule was written to '${file}'.`,
    search: 'Search',
    searchPh: 'name / body / file',
    sourceMd: 'Source md',
    all: 'All',
    checking: 'Checking',
    autoAll: '⚙️ Automatic (all)',
    coverHint:
      'These rules are abstract, so they cannot be machine-checked. To make one checkable, append an explicit pattern to the rule text: ',
    coverHintForbid: ' (a matching line is a violation) or ',
    coverHintRequire: ' (a violation when the file has no match at all).',
    ruleInactive: 'inactive',
    noRulesAtAll: 'No rules in the md files.',
    noRulesMatch: 'No rule matches the filter.',
    areaFrontend: 'Frontend',
    areaBackend: 'Backend',
    areaGeneral: 'General',
    mdFiles: 'md Files',
    newMdFile: 'New md file',
    create: 'Create',
    resetFromProject: "↻ Reset from the project's files",
    createdOk: (name: string) => `✅ '${name}' created.`,
    updatedOk: (name: string) => `✅ '${name}' updated.`,
    resetOk: "↻ Reloaded from the project's md files.",
    view: '👁 View',
    edit: '✏ Edit',
    save: 'Save',
    download: '⬇ Download',
    deleteBtn: 'Delete',
    editHint: 'Switch to ✏ Edit to make changes.',
    savedInBrowser: 'Changes are stored in the browser.',
    permanentHint: (file: string) => ` To make it permanent, use Download → replace src/rules-md/${file}.`,
    pickFileHint: 'Pick an md file on the left to edit, or create a new one.',
    confirmDeleteFile: (name: string) => `Delete '${name}'? (browser copy only)`,
    confirmResetAll: 'Discard all md changes and reload from the project files?',
  },
}

/** Aktif dildeki Code Review arayüz metinleri. */
export function ui(): (typeof UI)['tr'] {
  return UI[crLang()]
}
